/*
 Highcharts JS v5.0.14-modified (2017-09-22)

 3D features for Highcharts JS

 @license: www.highcharts.com/license
*/
(function(t){"object"===typeof module&&module.exports?module.exports=t:t(Highcharts)})(function(t){(function(c){var w=c.deg2rad,y=c.pick;c.perspective=function(x,B,A){var v=B.options.chart.options3d,q=A?B.inverted:!1,g=B.plotWidth/2,z=B.plotHeight/2,k=v.depth/2,b=y(v.depth,1)*y(v.viewDistance,0),a=B.scale3d||1,l=w*v.beta*(q?-1:1),v=w*v.alpha*(q?-1:1),f=Math.cos(v),h=Math.cos(-l),d=Math.sin(v),p=Math.sin(-l);A||(g+=B.plotLeft,z+=B.plotTop);return c.map(x,function(m){var c,l;l=(q?m.y:m.x)-g;var n=(q?
m.x:m.y)-z,D=(m.z||0)-k;c=h*l-p*D;m=-d*p*l+f*n-h*d*D;l=f*p*l+d*n+f*h*D;n=0<b&&b<Number.POSITIVE_INFINITY?b/(l+k+b):1;c=c*n*a+g;m=m*n*a+z;return{x:q?m:c,y:q?c:m,z:l*a+k}})};c.pointCameraDistance=function(c,w){var x=w.options.chart.options3d,v=w.plotWidth/2;w=w.plotHeight/2;x=y(x.depth,1)*y(x.viewDistance,0)+x.depth;return Math.sqrt(Math.pow(v-c.plotX,2)+Math.pow(w-c.plotY,2)+Math.pow(x-c.plotZ,2))};c.shapeArea=function(c){var x=0,w,v;for(w=0;w<c.length;w++)v=(w+1)%c.length,x+=c[w].x*c[v].y-c[v].x*
c[w].y;return x/2};c.shapeArea3d=function(w,y,A){return c.shapeArea(c.perspective(w,y,A))}})(t);(function(c){function w(a,d,e,h,b,f,c,m){var n=[],D=f-b;return f>b&&f-b>Math.PI/2+.0001?(n=n.concat(w(a,d,e,h,b,b+Math.PI/2,c,m)),n=n.concat(w(a,d,e,h,b+Math.PI/2,f,c,m))):f<b&&b-f>Math.PI/2+.0001?(n=n.concat(w(a,d,e,h,b,b-Math.PI/2,c,m)),n=n.concat(w(a,d,e,h,b-Math.PI/2,f,c,m))):["C",a+e*Math.cos(b)-e*u*D*Math.sin(b)+c,d+h*Math.sin(b)+h*u*D*Math.cos(b)+m,a+e*Math.cos(f)+e*u*D*Math.sin(f)+c,d+h*Math.sin(f)-
h*u*D*Math.cos(f)+m,a+e*Math.cos(f)+c,d+h*Math.sin(f)+m]}var y=Math.cos,x=Math.PI,B=Math.sin,A=c.animObject,v=c.charts,q=c.color,g=c.defined,z=c.deg2rad,k=c.each,b=c.extend,a=c.inArray,l=c.map,f=c.merge,h=c.perspective,d=c.pick,p=c.SVGElement,m=c.SVGRenderer,r=c.wrap,u=4*(Math.sqrt(2)-1)/3/(x/2);r(m.prototype,"init",function(a){a.apply(this,[].slice.call(arguments,1));k([{name:"darker",slope:.6},{name:"brighter",slope:1.4}],function(a){this.definition({tagName:"filter",id:"highcharts-"+a.name,children:[{tagName:"feComponentTransfer",
children:[{tagName:"feFuncR",type:"linear",slope:a.slope},{tagName:"feFuncG",type:"linear",slope:a.slope},{tagName:"feFuncB",type:"linear",slope:a.slope}]}]})},this)});m.prototype.toLinePath=function(a,d){var e=[];k(a,function(a){e.push("L",a.x,a.y)});a.length&&(e[0]="M",d&&e.push("Z"));return e};m.prototype.toLineSegments=function(a){var d=[],e=!0;k(a,function(a){d.push(e?"M":"L",a.x,a.y);e=!e});return d};m.prototype.face3d=function(a){var b=this,e=this.createElement("path");e.vertexes=[];e.insidePlotArea=
!1;e.enabled=!0;r(e,"attr",function(a,e){if("object"===typeof e&&(g(e.enabled)||g(e.vertexes)||g(e.insidePlotArea))){this.enabled=d(e.enabled,this.enabled);this.vertexes=d(e.vertexes,this.vertexes);this.insidePlotArea=d(e.insidePlotArea,this.insidePlotArea);delete e.enabled;delete e.vertexes;delete e.insidePlotArea;var f=h(this.vertexes,v[b.chartIndex],this.insidePlotArea),m=b.toLinePath(f,!0),f=c.shapeArea(f),f=this.enabled&&0<f?"visible":"hidden";e.d=m;e.visibility=f}return a.apply(this,[].slice.call(arguments,
1))});r(e,"animate",function(a,e){if("object"===typeof e&&(g(e.enabled)||g(e.vertexes)||g(e.insidePlotArea))){this.enabled=d(e.enabled,this.enabled);this.vertexes=d(e.vertexes,this.vertexes);this.insidePlotArea=d(e.insidePlotArea,this.insidePlotArea);delete e.enabled;delete e.vertexes;delete e.insidePlotArea;var f=h(this.vertexes,v[b.chartIndex],this.insidePlotArea),m=b.toLinePath(f,!0),f=c.shapeArea(f),f=this.enabled&&0<f?"visible":"hidden";e.d=m;this.attr("visibility",f)}return a.apply(this,[].slice.call(arguments,
1))});return e.attr(a)};m.prototype.polyhedron=function(a){var d=this,e=this.g(),b=e.destroy;e.faces=[];e.destroy=function(){for(var a=0;a<e.faces.length;a++)e.faces[a].destroy();return b.call(this)};r(e,"attr",function(a,b,f,h,c){if("object"===typeof b&&g(b.faces)){for(;e.faces.length>b.faces.length;)e.faces.pop().destroy();for(;e.faces.length<b.faces.length;)e.faces.push(d.face3d().add(e));for(var m=0;m<b.faces.length;m++)e.faces[m].attr(b.faces[m],null,h,c);delete b.faces}return a.apply(this,[].slice.call(arguments,
1))});r(e,"animate",function(a,b,f,h){if(b&&b.faces){for(;e.faces.length>b.faces.length;)e.faces.pop().destroy();for(;e.faces.length<b.faces.length;)e.faces.push(d.face3d().add(e));for(var c=0;c<b.faces.length;c++)e.faces[c].animate(b.faces[c],f,h);delete b.faces}return a.apply(this,[].slice.call(arguments,1))});return e.attr(a)};m.prototype.cuboid=function(a){var d=this.g(),e=d.destroy;a=this.cuboidPath(a);d.front=this.path(a[0]).attr({"class":"highcharts-3d-front"}).add(d);d.top=this.path(a[1]).attr({"class":"highcharts-3d-top"}).add(d);
d.side=this.path(a[2]).attr({"class":"highcharts-3d-side"}).add(d);d.fillSetter=function(a){this.front.attr({fill:a});this.top.attr({fill:q(a).brighten(.1).get()});this.side.attr({fill:q(a).brighten(-.1).get()});this.color=a;d.fill=a;return this};d.opacitySetter=function(a){this.front.attr({opacity:a});this.top.attr({opacity:a});this.side.attr({opacity:a});return this};d.attr=function(a,d,e,b){if("string"===typeof a&&"undefined"!==typeof d){var f=a;a={};a[f]=d}if(a.shapeArgs||g(a.x))a=this.renderer.cuboidPath(a.shapeArgs||
a),this.front.attr({d:a[0]}),this.top.attr({d:a[1]}),this.side.attr({d:a[2]});else return p.prototype.attr.call(this,a,void 0,e,b);return this};d.animate=function(a,d,e){g(a.x)&&g(a.y)?(a=this.renderer.cuboidPath(a),this.front.animate({d:a[0]},d,e),this.top.animate({d:a[1]},d,e),this.side.animate({d:a[2]},d,e),this.attr({zIndex:-a[3]})):a.opacity?(this.front.animate(a,d,e),this.top.animate(a,d,e),this.side.animate(a,d,e)):p.prototype.animate.call(this,a,d,e);return this};d.destroy=function(){this.front.destroy();
this.top.destroy();this.side.destroy();return e.call(this)};d.attr({zIndex:-a[3]});return d};c.SVGRenderer.prototype.cuboidPath=function(a){function d(a){return q[a]}var e=a.x,b=a.y,f=a.z,m=a.height,p=a.width,k=a.depth,n=v[this.chartIndex],r,z,u=n.options.chart.options3d.alpha,g=0,q=[{x:e,y:b,z:f},{x:e+p,y:b,z:f},{x:e+p,y:b+m,z:f},{x:e,y:b+m,z:f},{x:e,y:b+m,z:f+k},{x:e+p,y:b+m,z:f+k},{x:e+p,y:b,z:f+k},{x:e,y:b,z:f+k}],q=h(q,n,a.insidePlotArea);z=function(a,e){var b=[[],-1];a=l(a,d);e=l(e,d);0>c.shapeArea(a)?
b=[a,0]:0>c.shapeArea(e)&&(b=[e,1]);return b};r=z([3,2,1,0],[7,6,5,4]);a=r[0];p=r[1];r=z([1,6,7,0],[4,5,2,3]);m=r[0];k=r[1];r=z([1,2,5,6],[0,7,4,3]);z=r[0];r=r[1];1===r?g+=1E4*(1E3-e):r||(g+=1E4*e);g+=10*(!k||0<=u&&180>=u||360>u&&357.5<u?n.plotHeight-b:10+b);1===p?g+=100*f:p||(g+=100*(1E3-f));g=-Math.round(g);return[this.toLinePath(a,!0),this.toLinePath(m,!0),this.toLinePath(z,!0),g]};c.SVGRenderer.prototype.arc3d=function(h){function c(d){var e=!1,b={};d=f(d);for(var h in d)-1!==a(h,l)&&(b[h]=d[h],
delete d[h],e=!0);return e?b:!1}var e=this.g(),m=e.renderer,l="x y r innerR start end".split(" ");h=f(h);h.alpha*=z;h.beta*=z;e.top=m.path();e.side1=m.path();e.side2=m.path();e.inn=m.path();e.out=m.path();e.onAdd=function(){var a=e.parentGroup,d=e.attr("class");e.top.add(e);k(["out","inn","side1","side2"],function(b){e[b].attr({"class":d+" highcharts-3d-side"}).add(a)})};k(["addClass","removeClass"],function(a){e[a]=function(){var d=arguments;k(["top","out","inn","side1","side2"],function(b){e[b][a].apply(e[b],
d)})}});e.setPaths=function(a){var d=e.renderer.arc3dPath(a),b=100*d.zTop;e.attribs=a;e.top.attr({d:d.top,zIndex:d.zTop});e.inn.attr({d:d.inn,zIndex:d.zInn});e.out.attr({d:d.out,zIndex:d.zOut});e.side1.attr({d:d.side1,zIndex:d.zSide1});e.side2.attr({d:d.side2,zIndex:d.zSide2});e.zIndex=b;e.attr({zIndex:b});a.center&&(e.top.setRadialReference(a.center),delete a.center)};e.setPaths(h);e.fillSetter=function(a){var d=q(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:d});this.side2.attr({fill:d});
this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:a});return this};k(["opacity","translateX","translateY","visibility"],function(a){e[a+"Setter"]=function(a,d){e[d]=a;k(["out","inn","side1","side2","top"],function(b){e[b].attr(d,a)})}});r(e,"attr",function(a,d){var f;"object"===typeof d&&(f=c(d))&&(b(e.attribs,f),e.setPaths(e.attribs));return a.apply(this,[].slice.call(arguments,1))});r(e,"animate",function(a,e,b,h){var m,p=this.attribs,k;delete e.center;delete e.z;delete e.depth;
delete e.alpha;delete e.beta;k=A(d(b,this.renderer.globalAnimation));k.duration&&(m=c(e),e.dummy=1,m&&(k.step=function(a,e){function b(a){return p[a]+(d(m[a],p[a])-p[a])*e.pos}"dummy"===e.prop&&e.elem.setPaths(f(p,{x:b("x"),y:b("y"),r:b("r"),innerR:b("innerR"),start:b("start"),end:b("end")}))}),b=k);return a.call(this,e,b,h)});e.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();p.prototype.destroy.call(this)};e.hide=function(){this.top.hide();
this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};e.show=function(){this.top.show();this.out.show();this.inn.show();this.side1.show();this.side2.show()};return e};m.prototype.arc3dPath=function(a){function d(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var e=a.x,b=a.y,f=a.start,h=a.end-.00001,m=a.r,c=a.innerR,p=a.depth,k=a.alpha,l=a.beta,r=Math.cos(f),z=Math.sin(f);a=Math.cos(h);var u=Math.sin(h),n=m*Math.cos(l),m=m*Math.cos(k),g=c*Math.cos(l),v=c*Math.cos(k),c=p*Math.sin(l),
q=p*Math.sin(k),p=["M",e+n*r,b+m*z],p=p.concat(w(e,b,n,m,f,h,0,0)),p=p.concat(["L",e+g*a,b+v*u]),p=p.concat(w(e,b,g,v,h,f,0,0)),p=p.concat(["Z"]),A=0<l?Math.PI/2:0,l=0<k?0:Math.PI/2,A=f>-A?f:h>-A?-A:f,C=h<x-l?h:f<x-l?x-l:h,t=2*x-l,k=["M",e+n*y(A),b+m*B(A)],k=k.concat(w(e,b,n,m,A,C,0,0));h>t&&f<t?(k=k.concat(["L",e+n*y(C)+c,b+m*B(C)+q]),k=k.concat(w(e,b,n,m,C,t,c,q)),k=k.concat(["L",e+n*y(t),b+m*B(t)]),k=k.concat(w(e,b,n,m,t,h,0,0)),k=k.concat(["L",e+n*y(h)+c,b+m*B(h)+q]),k=k.concat(w(e,b,n,m,h,t,
c,q)),k=k.concat(["L",e+n*y(t),b+m*B(t)]),k=k.concat(w(e,b,n,m,t,C,0,0))):h>x-l&&f<x-l&&(k=k.concat(["L",e+n*Math.cos(C)+c,b+m*Math.sin(C)+q]),k=k.concat(w(e,b,n,m,C,h,c,q)),k=k.concat(["L",e+n*Math.cos(h),b+m*Math.sin(h)]),k=k.concat(w(e,b,n,m,h,C,0,0)));k=k.concat(["L",e+n*Math.cos(C)+c,b+m*Math.sin(C)+q]);k=k.concat(w(e,b,n,m,C,A,c,q));k=k.concat(["Z"]);l=["M",e+g*r,b+v*z];l=l.concat(w(e,b,g,v,f,h,0,0));l=l.concat(["L",e+g*Math.cos(h)+c,b+v*Math.sin(h)+q]);l=l.concat(w(e,b,g,v,h,f,c,q));l=l.concat(["Z"]);
r=["M",e+n*r,b+m*z,"L",e+n*r+c,b+m*z+q,"L",e+g*r+c,b+v*z+q,"L",e+g*r,b+v*z,"Z"];e=["M",e+n*a,b+m*u,"L",e+n*a+c,b+m*u+q,"L",e+g*a+c,b+v*u+q,"L",e+g*a,b+v*u,"Z"];u=Math.atan2(q,-c);b=Math.abs(h+u);a=Math.abs(f+u);f=Math.abs((f+h)/2+u);b=d(b);a=d(a);f=d(f);f*=1E5;h=1E5*a;b*=1E5;return{top:p,zTop:1E5*Math.PI+1,out:k,zOut:Math.max(f,h,b),inn:l,zInn:Math.max(f,h,b),side1:r,zSide1:.99*b,side2:e,zSide2:.99*h}}})(t);(function(c){function w(c,k){var b=c.plotLeft,a=c.plotWidth+b,l=c.plotTop,f=c.plotHeight+l,
h=b+c.plotWidth/2,d=l+c.plotHeight/2,p=Number.MAX_VALUE,m=-Number.MAX_VALUE,r=Number.MAX_VALUE,u=-Number.MAX_VALUE,n,z=1;n=[{x:b,y:l,z:0},{x:b,y:l,z:k}];x([0,1],function(d){n.push({x:a,y:n[d].y,z:n[d].z})});x([0,1,2,3],function(a){n.push({x:n[a].x,y:f,z:n[a].z})});n=A(n,c,!1);x(n,function(a){p=Math.min(p,a.x);m=Math.max(m,a.x);r=Math.min(r,a.y);u=Math.max(u,a.y)});b>p&&(z=Math.min(z,1-Math.abs((b+h)/(p+h))%1));a<m&&(z=Math.min(z,(a-h)/(m-h)));l>r&&(z=0>r?Math.min(z,(l+d)/(-r+l+d)):Math.min(z,1-(l+
d)/(r+d)%1));f<u&&(z=Math.min(z,Math.abs((f-d)/(u-d))));return z}var y=c.Chart,x=c.each,B=c.merge,A=c.perspective,v=c.pick,q=c.wrap;y.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};y.prototype.propsRequireDirtyBox.push("chart.options3d");y.prototype.propsRequireUpdateSeries.push("chart.options3d");c.wrap(c.Chart.prototype,"isInsidePlot",function(c){return this.is3d()||c.apply(this,[].slice.call(arguments,1))});var g=c.getOptions();B(!0,g,{chart:{options3d:{enabled:!1,
alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:"default",frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}});q(y.prototype,"getContainer",function(c){c.apply(this,[].slice.call(arguments,1));this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"})});q(y.prototype,"setClassName",function(c){c.apply(this,[].slice.call(arguments,1));
this.is3d()&&(this.container.className+=" highcharts-3d-chart")});c.wrap(c.Chart.prototype,"setChartSize",function(c){var k=this.options.chart.options3d;c.apply(this,[].slice.call(arguments,1));if(this.is3d()){var b=this.inverted,a=this.clipBox,l=this.margin;a[b?"y":"x"]=-(l[3]||0);a[b?"x":"y"]=-(l[0]||0);a[b?"height":"width"]=this.chartWidth+(l[3]||0)+(l[1]||0);a[b?"width":"height"]=this.chartHeight+(l[0]||0)+(l[2]||0);this.scale3d=1;!0===k.fitToPlot&&(this.scale3d=w(this,k.depth))}});q(y.prototype,
"redraw",function(c){this.is3d()&&(this.isDirtyBox=!0,this.frame3d=this.get3dFrame());c.apply(this,[].slice.call(arguments,1))});q(y.prototype,"render",function(c){this.is3d()&&(this.frame3d=this.get3dFrame());c.apply(this,[].slice.call(arguments,1))});q(y.prototype,"renderSeries",function(c){var k=this.series.length;if(this.is3d())for(;k--;)c=this.series[k],c.translate(),c.render();else c.call(this)});q(y.prototype,"drawChartBox",function(z){if(this.is3d()){var k=this.renderer,b=this.options.chart.options3d,
a=this.get3dFrame(),l=this.plotLeft,f=this.plotLeft+this.plotWidth,h=this.plotTop,d=this.plotTop+this.plotHeight,b=b.depth,p=l-(a.left.visible?a.left.size:0),m=f+(a.right.visible?a.right.size:0),r=h-(a.top.visible?a.top.size:0),u=d+(a.bottom.visible?a.bottom.size:0),n=0-(a.front.visible?a.front.size:0),g=b+(a.back.visible?a.back.size:0),e=this.hasRendered?"animate":"attr";this.frame3d=a;this.frameShapes||(this.frameShapes={bottom:k.polyhedron().add(),top:k.polyhedron().add(),left:k.polyhedron().add(),
right:k.polyhedron().add(),back:k.polyhedron().add(),front:k.polyhedron().add()});this.frameShapes.bottom[e]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:a.bottom.frontFacing?-1E3:1E3,faces:[{fill:c.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:p,y:u,z:n},{x:m,y:u,z:n},{x:m,y:u,z:g},{x:p,y:u,z:g}],enabled:a.bottom.visible},{fill:c.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:l,y:d,z:b},{x:f,y:d,z:b},{x:f,y:d,z:0},{x:l,y:d,z:0}],enabled:a.bottom.visible},{fill:c.color(a.bottom.color).brighten(-.1).get(),
vertexes:[{x:p,y:u,z:n},{x:p,y:u,z:g},{x:l,y:d,z:b},{x:l,y:d,z:0}],enabled:a.bottom.visible&&!a.left.visible},{fill:c.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:m,y:u,z:g},{x:m,y:u,z:n},{x:f,y:d,z:0},{x:f,y:d,z:b}],enabled:a.bottom.visible&&!a.right.visible},{fill:c.color(a.bottom.color).get(),vertexes:[{x:m,y:u,z:n},{x:p,y:u,z:n},{x:l,y:d,z:0},{x:f,y:d,z:0}],enabled:a.bottom.visible&&!a.front.visible},{fill:c.color(a.bottom.color).get(),vertexes:[{x:p,y:u,z:g},{x:m,y:u,z:g},{x:f,y:d,
z:b},{x:l,y:d,z:b}],enabled:a.bottom.visible&&!a.back.visible}]});this.frameShapes.top[e]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:a.top.frontFacing?-1E3:1E3,faces:[{fill:c.color(a.top.color).brighten(.1).get(),vertexes:[{x:p,y:r,z:g},{x:m,y:r,z:g},{x:m,y:r,z:n},{x:p,y:r,z:n}],enabled:a.top.visible},{fill:c.color(a.top.color).brighten(.1).get(),vertexes:[{x:l,y:h,z:0},{x:f,y:h,z:0},{x:f,y:h,z:b},{x:l,y:h,z:b}],enabled:a.top.visible},{fill:c.color(a.top.color).brighten(-.1).get(),
vertexes:[{x:p,y:r,z:g},{x:p,y:r,z:n},{x:l,y:h,z:0},{x:l,y:h,z:b}],enabled:a.top.visible&&!a.left.visible},{fill:c.color(a.top.color).brighten(-.1).get(),vertexes:[{x:m,y:r,z:n},{x:m,y:r,z:g},{x:f,y:h,z:b},{x:f,y:h,z:0}],enabled:a.top.visible&&!a.right.visible},{fill:c.color(a.top.color).get(),vertexes:[{x:p,y:r,z:n},{x:m,y:r,z:n},{x:f,y:h,z:0},{x:l,y:h,z:0}],enabled:a.top.visible&&!a.front.visible},{fill:c.color(a.top.color).get(),vertexes:[{x:m,y:r,z:g},{x:p,y:r,z:g},{x:l,y:h,z:b},{x:f,y:h,z:b}],
enabled:a.top.visible&&!a.back.visible}]});this.frameShapes.left[e]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:a.left.frontFacing?-1E3:1E3,faces:[{fill:c.color(a.left.color).brighten(.1).get(),vertexes:[{x:p,y:u,z:n},{x:l,y:d,z:0},{x:l,y:d,z:b},{x:p,y:u,z:g}],enabled:a.left.visible&&!a.bottom.visible},{fill:c.color(a.left.color).brighten(.1).get(),vertexes:[{x:p,y:r,z:g},{x:l,y:h,z:b},{x:l,y:h,z:0},{x:p,y:r,z:n}],enabled:a.left.visible&&!a.top.visible},{fill:c.color(a.left.color).brighten(-.1).get(),
vertexes:[{x:p,y:u,z:g},{x:p,y:r,z:g},{x:p,y:r,z:n},{x:p,y:u,z:n}],enabled:a.left.visible},{fill:c.color(a.left.color).brighten(-.1).get(),vertexes:[{x:l,y:h,z:b},{x:l,y:d,z:b},{x:l,y:d,z:0},{x:l,y:h,z:0}],enabled:a.left.visible},{fill:c.color(a.left.color).get(),vertexes:[{x:p,y:u,z:n},{x:p,y:r,z:n},{x:l,y:h,z:0},{x:l,y:d,z:0}],enabled:a.left.visible&&!a.front.visible},{fill:c.color(a.left.color).get(),vertexes:[{x:p,y:r,z:g},{x:p,y:u,z:g},{x:l,y:d,z:b},{x:l,y:h,z:b}],enabled:a.left.visible&&!a.back.visible}]});
this.frameShapes.right[e]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:a.right.frontFacing?-1E3:1E3,faces:[{fill:c.color(a.right.color).brighten(.1).get(),vertexes:[{x:m,y:u,z:g},{x:f,y:d,z:b},{x:f,y:d,z:0},{x:m,y:u,z:n}],enabled:a.right.visible&&!a.bottom.visible},{fill:c.color(a.right.color).brighten(.1).get(),vertexes:[{x:m,y:r,z:n},{x:f,y:h,z:0},{x:f,y:h,z:b},{x:m,y:r,z:g}],enabled:a.right.visible&&!a.top.visible},{fill:c.color(a.right.color).brighten(-.1).get(),vertexes:[{x:f,
y:h,z:0},{x:f,y:d,z:0},{x:f,y:d,z:b},{x:f,y:h,z:b}],enabled:a.right.visible},{fill:c.color(a.right.color).brighten(-.1).get(),vertexes:[{x:m,y:u,z:n},{x:m,y:r,z:n},{x:m,y:r,z:g},{x:m,y:u,z:g}],enabled:a.right.visible},{fill:c.color(a.right.color).get(),vertexes:[{x:m,y:r,z:n},{x:m,y:u,z:n},{x:f,y:d,z:0},{x:f,y:h,z:0}],enabled:a.right.visible&&!a.front.visible},{fill:c.color(a.right.color).get(),vertexes:[{x:m,y:u,z:g},{x:m,y:r,z:g},{x:f,y:h,z:b},{x:f,y:d,z:b}],enabled:a.right.visible&&!a.back.visible}]});
this.frameShapes.back[e]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:a.back.frontFacing?-1E3:1E3,faces:[{fill:c.color(a.back.color).brighten(.1).get(),vertexes:[{x:m,y:u,z:g},{x:p,y:u,z:g},{x:l,y:d,z:b},{x:f,y:d,z:b}],enabled:a.back.visible&&!a.bottom.visible},{fill:c.color(a.back.color).brighten(.1).get(),vertexes:[{x:p,y:r,z:g},{x:m,y:r,z:g},{x:f,y:h,z:b},{x:l,y:h,z:b}],enabled:a.back.visible&&!a.top.visible},{fill:c.color(a.back.color).brighten(-.1).get(),vertexes:[{x:p,y:u,
z:g},{x:p,y:r,z:g},{x:l,y:h,z:b},{x:l,y:d,z:b}],enabled:a.back.visible&&!a.left.visible},{fill:c.color(a.back.color).brighten(-.1).get(),vertexes:[{x:m,y:r,z:g},{x:m,y:u,z:g},{x:f,y:d,z:b},{x:f,y:h,z:b}],enabled:a.back.visible&&!a.right.visible},{fill:c.color(a.back.color).get(),vertexes:[{x:l,y:h,z:b},{x:f,y:h,z:b},{x:f,y:d,z:b},{x:l,y:d,z:b}],enabled:a.back.visible},{fill:c.color(a.back.color).get(),vertexes:[{x:p,y:u,z:g},{x:m,y:u,z:g},{x:m,y:r,z:g},{x:p,y:r,z:g}],enabled:a.back.visible}]});this.frameShapes.front[e]({"class":"highcharts-3d-frame highcharts-3d-frame-front",
zIndex:a.front.frontFacing?-1E3:1E3,faces:[{fill:c.color(a.front.color).brighten(.1).get(),vertexes:[{x:p,y:u,z:n},{x:m,y:u,z:n},{x:f,y:d,z:0},{x:l,y:d,z:0}],enabled:a.front.visible&&!a.bottom.visible},{fill:c.color(a.front.color).brighten(.1).get(),vertexes:[{x:m,y:r,z:n},{x:p,y:r,z:n},{x:l,y:h,z:0},{x:f,y:h,z:0}],enabled:a.front.visible&&!a.top.visible},{fill:c.color(a.front.color).brighten(-.1).get(),vertexes:[{x:p,y:r,z:n},{x:p,y:u,z:n},{x:l,y:d,z:0},{x:l,y:h,z:0}],enabled:a.front.visible&&!a.left.visible},
{fill:c.color(a.front.color).brighten(-.1).get(),vertexes:[{x:m,y:u,z:n},{x:m,y:r,z:n},{x:f,y:h,z:0},{x:f,y:d,z:0}],enabled:a.front.visible&&!a.right.visible},{fill:c.color(a.front.color).get(),vertexes:[{x:f,y:h,z:0},{x:l,y:h,z:0},{x:l,y:d,z:0},{x:f,y:d,z:0}],enabled:a.front.visible},{fill:c.color(a.front.color).get(),vertexes:[{x:m,y:u,z:n},{x:p,y:u,z:n},{x:p,y:r,z:n},{x:m,y:r,z:n}],enabled:a.front.visible}]})}return z.apply(this,[].slice.call(arguments,1))});y.prototype.retrieveStacks=function(c){var k=
this.series,b={},a,l=1;x(this.series,function(f){a=v(f.options.stack,c?0:k.length-1-f.index);b[a]?b[a].series.push(f):(b[a]={series:[f],position:l},l++)});b.totalStacks=l+1;return b};y.prototype.get3dFrame=function(){var g=this,k=g.options.chart.options3d,b=k.frame,a=g.plotLeft,l=g.plotLeft+g.plotWidth,f=g.plotTop,h=g.plotTop+g.plotHeight,d=k.depth,p=function(a){a=c.shapeArea3d(a,g);return.5<a?1:-.5>a?-1:0},m=p([{x:a,y:h,z:d},{x:l,y:h,z:d},{x:l,y:h,z:0},{x:a,y:h,z:0}]),r=p([{x:a,y:f,z:0},{x:l,y:f,
z:0},{x:l,y:f,z:d},{x:a,y:f,z:d}]),u=p([{x:a,y:f,z:0},{x:a,y:f,z:d},{x:a,y:h,z:d},{x:a,y:h,z:0}]),n=p([{x:l,y:f,z:d},{x:l,y:f,z:0},{x:l,y:h,z:0},{x:l,y:h,z:d}]),q=p([{x:a,y:h,z:0},{x:l,y:h,z:0},{x:l,y:f,z:0},{x:a,y:f,z:0}]),p=p([{x:a,y:f,z:d},{x:l,y:f,z:d},{x:l,y:h,z:d},{x:a,y:h,z:d}]),e=!1,w=!1,y=!1,B=!1;x([].concat(g.xAxis,g.yAxis,g.zAxis),function(a){a&&(a.horiz?a.opposite?w=!0:e=!0:a.opposite?B=!0:y=!0)});var t=function(a,d,b){for(var e=["size","color","visible"],h={},f=0;f<e.length;f++)for(var c=
e[f],m=0;m<a.length;m++)if("object"===typeof a[m]){var k=a[m][c];if(void 0!==k&&null!==k){h[c]=k;break}}a=b;!0===h.visible||!1===h.visible?a=h.visible:"auto"===h.visible&&(a=0<d);return{size:v(h.size,1),color:v(h.color,"none"),frontFacing:0<d,visible:a}},b={bottom:t([b.bottom,b.top,b],m,e),top:t([b.top,b.bottom,b],r,w),left:t([b.left,b.right,b.side,b],u,y),right:t([b.right,b.left,b.side,b],n,B),back:t([b.back,b.front,b],p,!0),front:t([b.front,b.back,b],q,!1)};"auto"===k.axisLabelPosition?(n=function(a,
d){return a.visible!==d.visible||a.visible&&d.visible&&a.frontFacing!==d.frontFacing},k=[],n(b.left,b.front)&&k.push({y:(f+h)/2,x:a,z:0,xDir:{x:1,y:0,z:0}}),n(b.left,b.back)&&k.push({y:(f+h)/2,x:a,z:d,xDir:{x:0,y:0,z:-1}}),n(b.right,b.front)&&k.push({y:(f+h)/2,x:l,z:0,xDir:{x:0,y:0,z:1}}),n(b.right,b.back)&&k.push({y:(f+h)/2,x:l,z:d,xDir:{x:-1,y:0,z:0}}),m=[],n(b.bottom,b.front)&&m.push({x:(a+l)/2,y:h,z:0,xDir:{x:1,y:0,z:0}}),n(b.bottom,b.back)&&m.push({x:(a+l)/2,y:h,z:d,xDir:{x:-1,y:0,z:0}}),r=[],
n(b.top,b.front)&&r.push({x:(a+l)/2,y:f,z:0,xDir:{x:1,y:0,z:0}}),n(b.top,b.back)&&r.push({x:(a+l)/2,y:f,z:d,xDir:{x:-1,y:0,z:0}}),u=[],n(b.bottom,b.left)&&u.push({z:(0+d)/2,y:h,x:a,xDir:{x:0,y:0,z:-1}}),n(b.bottom,b.right)&&u.push({z:(0+d)/2,y:h,x:l,xDir:{x:0,y:0,z:1}}),h=[],n(b.top,b.left)&&h.push({z:(0+d)/2,y:f,x:a,xDir:{x:0,y:0,z:-1}}),n(b.top,b.right)&&h.push({z:(0+d)/2,y:f,x:l,xDir:{x:0,y:0,z:1}}),a=function(a,d,b){if(0===a.length)return null;if(1===a.length)return a[0];for(var e=0,h=A(a,g,!1),
f=1;f<h.length;f++)b*h[f][d]>b*h[e][d]?e=f:b*h[f][d]===b*h[e][d]&&h[f].z<h[e].z&&(e=f);return a[e]},b.axes={y:{left:a(k,"x",-1),right:a(k,"x",1)},x:{top:a(r,"y",-1),bottom:a(m,"y",1)},z:{top:a(h,"y",-1),bottom:a(u,"y",1)}}):b.axes={y:{left:{x:a,z:0,xDir:{x:1,y:0,z:0}},right:{x:l,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:f,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:h,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:y?l:a,y:f,xDir:y?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:y?l:a,y:h,xDir:y?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return b};
c.Fx.prototype.matrixSetter=function(){var g;if(1>this.pos&&(c.isArray(this.start)||c.isArray(this.end))){var k=this.start||[1,0,0,1,0,0],b=this.end||[1,0,0,1,0,0];g=[];for(var a=0;6>a;a++)g.push(this.pos*b[a]+(1-this.pos)*k[a])}else g=this.end;this.elem.attr(this.prop,g,null,!0)}})(t);(function(c){function w(a,d,f){if(!a.chart.is3d()||"colorAxis"===a.coll)return d;var c=a.chart,h=A*c.options.chart.options3d.alpha,l=A*c.options.chart.options3d.beta,p=k(f&&a.options.title.position3d,a.options.labels.position3d);
f=k(f&&a.options.title.skew3d,a.options.labels.skew3d);var g=c.frame3d,e=c.plotLeft,q=c.plotWidth+e,v=c.plotTop,w=c.plotHeight+v,c=!1,x=0,y=0,t={x:0,y:1,z:0};d=a.swapZ({x:d.x,y:d.y,z:0});if(a.isZAxis)if(a.opposite){if(null===g.axes.z.top)return{};y=d.y-v;d.x=g.axes.z.top.x;d.y=g.axes.z.top.y;e=g.axes.z.top.xDir;c=!g.top.frontFacing}else{if(null===g.axes.z.bottom)return{};y=d.y-w;d.x=g.axes.z.bottom.x;d.y=g.axes.z.bottom.y;e=g.axes.z.bottom.xDir;c=!g.bottom.frontFacing}else if(a.horiz)if(a.opposite){if(null===
g.axes.x.top)return{};y=d.y-v;d.y=g.axes.x.top.y;d.z=g.axes.x.top.z;e=g.axes.x.top.xDir;c=!g.top.frontFacing}else{if(null===g.axes.x.bottom)return{};y=d.y-w;d.y=g.axes.x.bottom.y;d.z=g.axes.x.bottom.z;e=g.axes.x.bottom.xDir;c=!g.bottom.frontFacing}else if(a.opposite){if(null===g.axes.y.right)return{};x=d.x-q;d.x=g.axes.y.right.x;d.z=g.axes.y.right.z;e=g.axes.y.right.xDir;e={x:e.z,y:e.y,z:-e.x}}else{if(null===g.axes.y.left)return{};x=d.x-e;d.x=g.axes.y.left.x;d.z=g.axes.y.left.z;e=g.axes.y.left.xDir}"chart"!==
p&&("flap"===p?a.horiz?(l=Math.sin(h),h=Math.cos(h),a.opposite&&(l=-l),c&&(l=-l),t={x:e.z*l,y:h,z:-e.x*l}):e={x:Math.cos(l),y:0,z:Math.sin(l)}:"ortho"===p?a.horiz?(t=Math.cos(h),p=Math.sin(l)*t,h=-Math.sin(h),l=-t*Math.cos(l),t={x:e.y*l-e.z*h,y:e.z*p-e.x*l,z:e.x*h-e.y*p},h=1/Math.sqrt(t.x*t.x+t.y*t.y+t.z*t.z),c&&(h=-h),t={x:h*t.x,y:h*t.y,z:h*t.z}):e={x:Math.cos(l),y:0,z:Math.sin(l)}:a.horiz?t={x:Math.sin(l)*Math.sin(h),y:Math.cos(h),z:-Math.cos(l)*Math.sin(h)}:e={x:Math.cos(l),y:0,z:Math.sin(l)});
d.x+=x*e.x+y*t.x;d.y+=x*e.y+y*t.y;d.z+=x*e.z+y*t.z;c=z([d],a.chart)[0];f?(0>b(z([d,{x:d.x+e.x,y:d.y+e.y,z:d.z+e.z},{x:d.x+t.x,y:d.y+t.y,z:d.z+t.z}],a.chart))&&(e={x:-e.x,y:-e.y,z:-e.z}),a=z([{x:d.x,y:d.y,z:d.z},{x:d.x+e.x,y:d.y+e.y,z:d.z+e.z},{x:d.x+t.x,y:d.y+t.y,z:d.z+t.z}],a.chart),c.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,c.x,c.y],c.matrix[4]-=c.x*c.matrix[0]+c.y*c.matrix[2],c.matrix[5]-=c.x*c.matrix[1]+c.y*c.matrix[3]):c.matrix=null;return c}var y,x=c.Axis,t=c.Chart,A=
c.deg2rad,v=c.each,q=c.extend,g=c.merge,z=c.perspective,k=c.pick,b=c.shapeArea,a=c.splat,l=c.Tick,f=c.wrap;g(!0,x.prototype.defaultOptions,{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}});f(x.prototype,"setOptions",function(a,d){a.call(this,d);this.chart.is3d()&&"colorAxis"!==this.coll&&(a=this.options,a.tickWidth=k(a.tickWidth,0),a.gridLineWidth=k(a.gridLineWidth,1))});f(x.prototype,"getPlotLinePath",function(a){var d=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d()||
"colorAxis"===this.coll||null===d)return d;var b=this.chart,c=b.options.chart.options3d,c=this.isZAxis?b.plotWidth:c.depth,b=b.frame3d,d=[this.swapZ({x:d[1],y:d[2],z:0}),this.swapZ({x:d[1],y:d[2],z:c}),this.swapZ({x:d[4],y:d[5],z:0}),this.swapZ({x:d[4],y:d[5],z:c})],c=[];this.horiz?(this.isZAxis?(b.left.visible&&c.push(d[0],d[2]),b.right.visible&&c.push(d[1],d[3])):(b.front.visible&&c.push(d[0],d[2]),b.back.visible&&c.push(d[1],d[3])),b.top.visible&&c.push(d[0],d[1]),b.bottom.visible&&c.push(d[2],
d[3])):(b.front.visible&&c.push(d[0],d[2]),b.back.visible&&c.push(d[1],d[3]),b.left.visible&&c.push(d[0],d[1]),b.right.visible&&c.push(d[2],d[3]));c=z(c,this.chart,!1);return this.chart.renderer.toLineSegments(c)});f(x.prototype,"getLinePath",function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))});f(x.prototype,"getPlotBandPath",function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var d=arguments,
b=d[2],c=[],d=this.getPlotLinePath(d[1]),b=this.getPlotLinePath(b);if(d&&b)for(var f=0;f<d.length;f+=6)c.push("M",d[f+1],d[f+2],"L",d[f+4],d[f+5],"L",b[f+4],b[f+5],"L",b[f+1],b[f+2],"Z");return c});f(l.prototype,"getMarkPath",function(a){var b=a.apply(this,[].slice.call(arguments,1)),b=[w(this.axis,{x:b[1],y:b[2],z:0}),w(this.axis,{x:b[4],y:b[5],z:0})];return this.axis.chart.renderer.toLineSegments(b)});f(l.prototype,"getLabelPosition",function(a){var b=a.apply(this,[].slice.call(arguments,1));return w(this.axis,
b)});f(x.prototype,"getTitlePosition",function(a){var b=a.apply(this,[].slice.call(arguments,1));return w(this,b,!0)});f(x.prototype,"drawCrosshair",function(a){var b=arguments;this.chart.is3d()&&"colorAxis"!==this.coll&&b[2]&&(b[2]={plotX:b[2].plotXold||b[2].plotX,plotY:b[2].plotYold||b[2].plotY});a.apply(this,[].slice.call(b,1))});f(x.prototype,"destroy",function(a){v(["backFrame","bottomFrame","sideFrame"],function(a){this[a]&&(this[a]=this[a].destroy())},this);a.apply(this,[].slice.call(arguments,
1))});x.prototype.swapZ=function(a,b){return this.isZAxis?(b=b?0:this.chart.plotLeft,{x:b+a.z,y:a.y,z:a.x-b}):a};y=c.ZAxis=function(){this.init.apply(this,arguments)};q(y.prototype,x.prototype);q(y.prototype,{isZAxis:!0,setOptions:function(a){a=g({offset:0,lineWidth:0},a);x.prototype.setOptions.call(this,a);this.coll="zAxis"},setAxisSize:function(){x.prototype.setAxisSize.call(this);this.width=this.len=this.chart.options.chart.options3d.depth;this.right=this.chart.chartWidth-this.width-this.left},
getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();v(a.series,function(d){if(d.visible||!b.options.chart.ignoreHiddenSeries)a.hasVisibleSeries=!0,d=d.zData,d.length&&(a.dataMin=Math.min(k(a.dataMin,d[0]),Math.min.apply(null,d)),a.dataMax=Math.max(k(a.dataMax,d[0]),Math.max.apply(null,d)))})}});f(t.prototype,"getAxes",function(b){var d=this,c=this.options,c=c.zAxis=a(c.zAxis||{});b.call(this);
d.is3d()&&(this.zAxis=[],v(c,function(a,b){a.index=b;a.isX=!0;(new y(d,a)).setScale()}))})})(t);(function(c){var w=c.each,t=c.perspective,x=c.pick,B=c.Series,A=c.seriesTypes,v=c.inArray,q=c.svg,g=c.wrap;g(A.column.prototype,"translate",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var k=this,b=k.chart,a=k.options,l=a.depth||25,f=(a.stacking?a.stack||0:k.index)*(l+(a.groupZPadding||1)),h=k.borderWidth%2?.5:0;b.inverted&&!k.yAxis.reversed&&(h*=-1);!1!==a.grouping&&(f=0);
f+=a.groupZPadding||1;w(k.data,function(a){if(null!==a.y){var d=a.shapeArgs,c=a.tooltipPos,g;w([["x","width"],["y","height"]],function(a){g=d[a[0]]-h;0>g&&(d[a[1]]+=d[a[0]]+h,d[a[0]]=-h,g=0);g+d[a[1]]>k[a[0]+"Axis"].len&&0!==d[a[1]]&&(d[a[1]]=k[a[0]+"Axis"].len-d[a[0]]);if(0!==d[a[1]]&&(d[a[0]]>=k[a[0]+"Axis"].len||d[a[0]]+d[a[1]]<=h))for(var b in d)d[b]=0});a.shapeType="cuboid";d.z=f;d.depth=l;d.insidePlotArea=!0;c=t([{x:c[0],y:c[1],z:f}],b,!0)[0];a.tooltipPos=[c.x,c.y]}});k.z=f}});g(A.column.prototype,
"animate",function(c){if(this.chart.is3d()){var k=arguments[1],b=this.yAxis,a=this,g=this.yAxis.reversed;q&&(k?w(a.data,function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,g||(a.shapeArgs.y=a.stackY?a.plotY+b.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(w(a.data,function(b){null!==b.y&&(b.shapeArgs.height=b.height,b.shapeArgs.y=b.shapey,b.graphic&&b.graphic.animate(b.shapeArgs,a.options.animation))}),this.drawDataLabels(),a.animate=
null))}else c.apply(this,[].slice.call(arguments,1))});g(A.column.prototype,"plotGroup",function(c,k,b,a,g,f){this.chart.is3d()&&f&&!this[k]&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(f)),this[k]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[k].survive=!0);return c.apply(this,Array.prototype.slice.call(arguments,1))});g(A.column.prototype,"setVisible",function(c,k){var b=this,a;b.chart.is3d()&&w(b.data,function(c){a=(c.visible=
c.options.visible=k=void 0===k?!c.visible:k)?"visible":"hidden";b.options.data[v(c,b.data)]=c.options;c.graphic&&c.graphic.attr({visibility:a})});c.apply(this,Array.prototype.slice.call(arguments,1))});g(A.column.prototype,"init",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var k=this.options,b=k.grouping,a=k.stacking,g=x(this.yAxis.options.reversedStacks,!0),f=0;if(void 0===b||b){b=this.chart.retrieveStacks(a);f=k.stack||0;for(a=0;a<b[f].series.length&&b[f].series[a]!==
this;a++);f=10*(b.totalStacks-b[f].position)+(g?a:-a);this.xAxis.reversed||(f=10*b.totalStacks-f)}k.zIndex=f}});g(B.prototype,"alignDataLabel",function(c){if(this.chart.is3d()&&("column"===this.type||"columnrange"===this.type)){var g=arguments[4],b={x:g.x,y:g.y,z:this.z},b=t([b],this.chart,!0)[0];g.x=b.x;g.y=b.y}c.apply(this,[].slice.call(arguments,1))});g(c.StackItem.prototype,"getStackBox",function(g,k){var b=g.apply(this,[].slice.call(arguments,1));if(k.is3d()){var a={x:b.x,y:b.y,z:0},a=c.perspective([a],
k,!0)[0];b.x=a.x;b.y=a.y}return b})})(t);(function(c){var w=c.deg2rad,t=c.each,x=c.seriesTypes,B=c.svg;c=c.wrap;c(x.pie.prototype,"translate",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var v=this,q=v.options,g=q.depth||0,z=v.chart.options.chart.options3d,k=z.alpha,b=z.beta,a=q.stacking?(q.stack||0)*g:v._i*g,a=a+g/2;!1!==q.grouping&&(a=0);t(v.data,function(c){var f=c.shapeArgs;c.shapeType="arc3d";f.z=a;f.depth=.75*g;f.alpha=k;f.beta=b;f.center=v.center;f=(f.end+f.start)/
2;c.slicedTranslation={translateX:Math.round(Math.cos(f)*q.slicedOffset*Math.cos(k*w)),translateY:Math.round(Math.sin(f)*q.slicedOffset*Math.cos(k*w))}})}});c(x.pie.prototype.pointClass.prototype,"haloPath",function(c){var v=arguments;return this.series.chart.is3d()?[]:c.call(this,v[1])});c(x.pie.prototype,"drawPoints",function(c){c.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&t(this.points,function(c){var q=c.graphic;if(q)q[c.y&&c.visible?"show":"hide"]()})});c(x.pie.prototype,"drawDataLabels",
function(c){if(this.chart.is3d()){var v=this.chart.options.chart.options3d;t(this.data,function(c){var g=c.shapeArgs,q=g.r,k=(g.start+g.end)/2,b=c.labelPos,a=-q*(1-Math.cos((g.alpha||v.alpha)*w))*Math.sin(k),l=q*(Math.cos((g.beta||v.beta)*w)-1)*Math.cos(k);t([0,2,4],function(c){b[c]+=l;b[c+1]+=a})})}c.apply(this,[].slice.call(arguments,1))});c(x.pie.prototype,"addPoint",function(c){c.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});c(x.pie.prototype,"animate",
function(c){if(this.chart.is3d()){var v=arguments[1],q=this.options.animation,g=this.center,t=this.group,k=this.markerGroup;B&&(!0===q&&(q={}),v?(t.oldtranslateX=t.translateX,t.oldtranslateY=t.translateY,v={translateX:g[0],translateY:g[1],scaleX:.001,scaleY:.001},t.attr(v),k&&(k.attrSetters=t.attrSetters,k.attr(v))):(v={translateX:t.oldtranslateX,translateY:t.oldtranslateY,scaleX:1,scaleY:1},t.animate(v,q),k&&k.animate(v,q),this.animate=null))}else c.apply(this,[].slice.call(arguments,1))})})(t);
(function(c){var t=c.perspective,y=c.pick,x=c.Point,B=c.seriesTypes,A=c.wrap;A(B.scatter.prototype,"translate",function(c){c.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var q=this.chart,g=y(this.zAxis,q.options.zAxis[0]),v=[],k,b,a;for(a=0;a<this.data.length;a++)k=this.data[a],b=g.isLog&&g.val2lin?g.val2lin(k.z):k.z,k.plotZ=g.translate(b),k.isInside=k.isInside?b>=g.min&&b<=g.max:!1,v.push({x:k.plotX,y:k.plotY,z:k.plotZ});q=t(v,q,!0);for(a=0;a<this.data.length;a++)k=this.data[a],g=
q[a],k.plotXold=k.plotX,k.plotYold=k.plotY,k.plotZold=k.plotZ,k.plotX=g.x,k.plotY=g.y,k.plotZ=g.z}});A(B.scatter.prototype,"init",function(c,q,g){q.is3d()&&(this.axisTypes=["xAxis","yAxis","zAxis"],this.pointArrayMap=["x","y","z"],this.parallelArrays=["x","y","z"],this.directTouch=!0);c=c.apply(this,[q,g]);this.chart.is3d()&&(this.tooltipOptions.pointFormat=this.userOptions.tooltip?this.userOptions.tooltip.pointFormat||"x: \x3cb\x3e{point.x}\x3c/b\x3e\x3cbr/\x3ey: \x3cb\x3e{point.y}\x3c/b\x3e\x3cbr/\x3ez: \x3cb\x3e{point.z}\x3c/b\x3e\x3cbr/\x3e":
"x: \x3cb\x3e{point.x}\x3c/b\x3e\x3cbr/\x3ey: \x3cb\x3e{point.y}\x3c/b\x3e\x3cbr/\x3ez: \x3cb\x3e{point.z}\x3c/b\x3e\x3cbr/\x3e");return c});A(B.scatter.prototype,"pointAttribs",function(t,q){var g=t.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&q&&(g.zIndex=c.pointCameraDistance(q,this.chart));return g});A(x.prototype,"applyOptions",function(c){var q=c.apply(this,[].slice.call(arguments,1));this.series.chart.is3d()&&void 0===q.z&&(q.z=0);return q})})(t)});