/*
 Highcharts JS v5.0.14-modified (2017-09-22)
 Highstock as a plugin for Highcharts

 (c) 2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(K){"object"===typeof module&&module.exports?module.exports=K:K(Highcharts)})(function(K){(function(a){var F=a.addEvent,t=a.Axis,z=a.Chart,B=a.css,E=a.dateFormat,w=a.defined,I=a.each,u=a.extend,p=a.noop,H=a.timeUnits,J=a.wrap;J(a.Series.prototype,"init",function(a){var d;a.apply(this,Array.prototype.slice.call(arguments,1));(d=this.xAxis)&&d.options.ordinal&&F(this,"updatedData",function(){delete d.ordinalIndex})});J(t.prototype,"getTimeTicks",function(a,d,b,h,k,m,f,g){var e=0,q,r,c={},v,
y,G,C=[],l=-Number.MAX_VALUE,n=this.options.tickPixelInterval;if(!this.options.ordinal&&!this.options.breaks||!m||3>m.length||void 0===b)return a.call(this,d,b,h,k);y=m.length;for(q=0;q<y;q++){G=q&&m[q-1]>h;m[q]<b&&(e=q);if(q===y-1||m[q+1]-m[q]>5*f||G){if(m[q]>l){for(r=a.call(this,d,m[e],m[q],k);r.length&&r[0]<=l;)r.shift();r.length&&(l=r[r.length-1]);C=C.concat(r)}e=q+1}if(G)break}a=r.info;if(g&&a.unitRange<=H.hour){q=C.length-1;for(e=1;e<q;e++)E("%d",C[e])!==E("%d",C[e-1])&&(c[C[e]]="day",v=!0);
v&&(c[C[0]]="day");a.higherRanks=c}C.info=a;if(g&&w(n)){g=a=C.length;q=[];var x;for(v=[];g--;)e=this.translate(C[g]),x&&(v[g]=x-e),q[g]=x=e;v.sort();v=v[Math.floor(v.length/2)];v<.6*n&&(v=null);g=C[a-1]>h?a-1:a;for(x=void 0;g--;)e=q[g],h=Math.abs(x-e),x&&h<.8*n&&(null===v||h<.8*v)?(c[C[g]]&&!c[C[g+1]]?(h=g+1,x=e):h=g,C.splice(h,1)):x=e}return C});u(t.prototype,{beforeSetTickPositions:function(){var a,d=[],b=!1,h,k=this.getExtremes(),m=k.min,f=k.max,g,D=this.isXAxis&&!!this.options.breaks,k=this.options.ordinal,
q=this.chart.options.chart.ignoreHiddenSeries;if(k||D){I(this.series,function(f,c){if(!(q&&!1===f.visible||!1===f.takeOrdinalPosition&&!D)&&(d=d.concat(f.processedXData),a=d.length,d.sort(function(c,f){return c-f}),a))for(c=a-1;c--;)d[c]===d[c+1]&&d.splice(c,1)});a=d.length;if(2<a){h=d[1]-d[0];for(g=a-1;g--&&!b;)d[g+1]-d[g]!==h&&(b=!0);!this.options.keepOrdinalPadding&&(d[0]-m>h||f-d[d.length-1]>h)&&(b=!0)}b?(this.ordinalPositions=d,h=this.ordinal2lin(Math.max(m,d[0]),!0),g=Math.max(this.ordinal2lin(Math.min(f,
d[d.length-1]),!0),1),this.ordinalSlope=f=(f-m)/(g-h),this.ordinalOffset=m-h*f):this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0}this.isOrdinal=k&&b;this.groupIntervalFactor=null},val2lin:function(a,d){var b=this.ordinalPositions;if(b){var h=b.length,k,e;for(k=h;k--;)if(b[k]===a){e=k;break}for(k=h-1;k--;)if(a>b[k]||0===k){a=(a-b[k])/(b[k+1]-b[k]);e=k+a;break}d=d?e:this.ordinalSlope*(e||0)+this.ordinalOffset}else d=a;return d},lin2val:function(a,d){var b=this.ordinalPositions;if(b){var h=
this.ordinalSlope,k=this.ordinalOffset,e=b.length-1,f;if(d)0>a?a=b[0]:a>e?a=b[e]:(e=Math.floor(a),f=a-e);else for(;e--;)if(d=h*e+k,a>=d){h=h*(e+1)+k;f=(a-d)/(h-d);break}return void 0!==f&&void 0!==b[e]?b[e]+(f?f*(b[e+1]-b[e]):0):a}return a},getExtendedPositions:function(){var a=this.chart,d=this.series[0].currentDataGrouping,b=this.ordinalIndex,h=d?d.count+d.unitName:"raw",k=this.getExtremes(),m,f;b||(b=this.ordinalIndex={});b[h]||(m={series:[],chart:a,getExtremes:function(){return{min:k.dataMin,
max:k.dataMax}},options:{ordinal:!0},val2lin:t.prototype.val2lin,ordinal2lin:t.prototype.ordinal2lin},I(this.series,function(g){f={xAxis:m,xData:g.xData,chart:a,destroyGroupedData:p};f.options={dataGrouping:d?{enabled:!0,forced:!0,approximation:"open",units:[[d.unitName,[d.count]]]}:{enabled:!1}};g.processData.apply(f);m.series.push(f)}),this.beforeSetTickPositions.apply(m),b[h]=m.ordinalPositions);return b[h]},getGroupIntervalFactor:function(a,d,b){var h;b=b.processedXData;var k=b.length,e=[];h=
this.groupIntervalFactor;if(!h){for(h=0;h<k-1;h++)e[h]=b[h+1]-b[h];e.sort(function(f,a){return f-a});e=e[Math.floor(k/2)];a=Math.max(a,b[0]);d=Math.min(d,b[k-1]);this.groupIntervalFactor=h=k*e/(d-a)}return h},postProcessTickInterval:function(a){var d=this.ordinalSlope;return d?this.options.breaks?this.closestPointRange:a/(d/this.closestPointRange):a}});t.prototype.ordinal2lin=t.prototype.val2lin;J(z.prototype,"pan",function(a,d){var b=this.xAxis[0],h=d.chartX,k=!1;if(b.options.ordinal&&b.series.length){var e=
this.mouseDownX,f=b.getExtremes(),g=f.dataMax,D=f.min,q=f.max,r=this.hoverPoints,c=b.closestPointRange,e=(e-h)/(b.translationSlope*(b.ordinalSlope||c)),v={ordinalPositions:b.getExtendedPositions()},c=b.lin2val,y=b.val2lin,G;v.ordinalPositions?1<Math.abs(e)&&(r&&I(r,function(c){c.setState()}),0>e?(r=v,G=b.ordinalPositions?b:v):(r=b.ordinalPositions?b:v,G=v),v=G.ordinalPositions,g>v[v.length-1]&&v.push(g),this.fixedRange=q-D,e=b.toFixedRange(null,null,c.apply(r,[y.apply(r,[D,!0])+e,!0]),c.apply(G,[y.apply(G,
[q,!0])+e,!0])),e.min>=Math.min(f.dataMin,D)&&e.max<=Math.max(g,q)&&b.setExtremes(e.min,e.max,!0,!1,{trigger:"pan"}),this.mouseDownX=h,B(this.container,{cursor:"move"})):k=!0}else k=!0;k&&a.apply(this,Array.prototype.slice.call(arguments,1))})})(K);(function(a){function F(){return Array.prototype.slice.call(arguments,1)}function t(a){a.apply(this);this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,z(this.pointArrayMap,["y"]))}var z=a.pick,B=a.wrap,E=a.each,w=a.extend,I=a.isArray,u=a.fireEvent,
p=a.Axis,H=a.Series;w(p.prototype,{isInBreak:function(a,e){var d=a.repeat||Infinity,b=a.from,h=a.to-a.from;e=e>=b?(e-b)%d:d-(b-e)%d;return a.inclusive?e<=h:e<h&&0!==e},isInAnyBreak:function(a,e){var d=this.options.breaks,b=d&&d.length,h,k,m;if(b){for(;b--;)this.isInBreak(d[b],a)&&(h=!0,k||(k=z(d[b].showPoints,this.isXAxis?!1:!0)));m=h&&e?h&&!k:h}return m}});B(p.prototype,"setTickPositions",function(a){a.apply(this,Array.prototype.slice.call(arguments,1));if(this.options.breaks){var e=this.tickPositions,
d=this.tickPositions.info,b=[],h;for(h=0;h<e.length;h++)this.isInAnyBreak(e[h])||b.push(e[h]);this.tickPositions=b;this.tickPositions.info=d}});B(p.prototype,"init",function(a,e,d){var b=this;d.breaks&&d.breaks.length&&(d.ordinal=!1);a.call(this,e,d);a=this.options.breaks;b.isBroken=I(a)&&!!a.length;b.isBroken&&(b.val2lin=function(a){var h=a,e,f;for(f=0;f<b.breakArray.length;f++)if(e=b.breakArray[f],e.to<=a)h-=e.len;else if(e.from>=a)break;else if(b.isInBreak(e,a)){h-=a-e.from;break}return h},b.lin2val=
function(a){var e,h;for(h=0;h<b.breakArray.length&&!(e=b.breakArray[h],e.from>=a);h++)e.to<a?a+=e.len:b.isInBreak(e,a)&&(a+=e.len);return a},b.setExtremes=function(a,b,e,f,g){for(;this.isInAnyBreak(a);)a-=this.closestPointRange;for(;this.isInAnyBreak(b);)b-=this.closestPointRange;p.prototype.setExtremes.call(this,a,b,e,f,g)},b.setAxisTranslation=function(a){p.prototype.setAxisTranslation.call(this,a);a=b.options.breaks;var e=[],h=[],f=0,g,d,q=b.userMin||b.min,r=b.userMax||b.max,c=z(b.pointRangePadding,
0),v,y;E(a,function(c){d=c.repeat||Infinity;b.isInBreak(c,q)&&(q+=c.to%d-q%d);b.isInBreak(c,r)&&(r-=r%d-c.from%d)});E(a,function(c){v=c.from;for(d=c.repeat||Infinity;v-d>q;)v-=d;for(;v<q;)v+=d;for(y=v;y<r;y+=d)e.push({value:y,move:"in"}),e.push({value:y+(c.to-c.from),move:"out",size:c.breakSize})});e.sort(function(c,a){return c.value===a.value?("in"===c.move?0:1)-("in"===a.move?0:1):c.value-a.value});g=0;v=q;E(e,function(c){g+="in"===c.move?1:-1;1===g&&"in"===c.move&&(v=c.value);0===g&&(h.push({from:v,
to:c.value,len:c.value-v-(c.size||0)}),f+=c.value-v-(c.size||0))});b.breakArray=h;b.unitLength=r-q-f+c;u(b,"afterBreaks");b.options.staticScale?b.transA=b.options.staticScale:b.unitLength&&(b.transA*=(r-b.min+c)/b.unitLength);c&&(b.minPixelPadding=b.transA*b.minPointOffset);b.min=q;b.max=r})});B(H.prototype,"generatePoints",function(a){a.apply(this,F(arguments));var e=this.xAxis,d=this.yAxis,b=this.points,h,k=b.length,m=this.options.connectNulls,f;if(e&&d&&(e.options.breaks||d.options.breaks))for(;k--;)h=
b[k],f=null===h.y&&!1===m,f||!e.isInAnyBreak(h.x,!0)&&!d.isInAnyBreak(h.y,!0)||(b.splice(k,1),this.data[k]&&this.data[k].destroyElements())});a.Series.prototype.drawBreaks=function(a,e){var d=this,b=d.points,h,k,m,f;a&&E(e,function(g){h=a.breakArray||[];k=a.isXAxis?a.min:z(d.options.threshold,a.min);E(b,function(b){f=z(b["stack"+g.toUpperCase()],b[g]);E(h,function(g){m=!1;if(k<g.from&&f>g.to||k>g.from&&f<g.from)m="pointBreak";else if(k<g.from&&f>g.from&&f<g.to||k>g.from&&f>g.to&&f<g.from)m="pointInBreak";
m&&u(a,m,{point:b,brk:g})})})})};a.Series.prototype.gappedPath=function(){var p=this.options.gapSize,e=this.points.slice(),d=e.length-1,b=this.yAxis,h;if(p&&0<d)for("value"!==this.options.gapUnit&&(p*=this.closestPointRange);d--;)e[d+1].x-e[d].x>p&&(h=(e[d].x+e[d+1].x)/2,e.splice(d+1,0,{isNull:!0,x:h}),this.options.stacking&&(h=b.stacks[this.stackKey][h]=new a.StackItem(b,b.options.stackLabels,!1,h,this.stack),h.total=0));return this.getGraphPath(e)};B(a.seriesTypes.column.prototype,"drawPoints",
t);B(a.Series.prototype,"drawPoints",t)})(K);(function(a){var F=a.arrayMax,t=a.arrayMin,z=a.Axis,B=a.defaultPlotOptions,E=a.defined,w=a.each,I=a.extend,u=a.format,p=a.isNumber,H=a.merge,J=a.pick,e=a.Point,d=a.Tooltip,b=a.wrap,h=a.Series.prototype,k=h.processData,m=h.generatePoints,f=h.destroy,g={approximation:"average",groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],
minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},D={line:{},spline:{},area:{},areaspline:{},column:{approximation:"sum",groupPixelWidth:10},arearange:{approximation:"range"},areasplinerange:{approximation:"range"},columnrange:{approximation:"range",groupPixelWidth:10},candlestick:{approximation:"ohlc",
groupPixelWidth:10},ohlc:{approximation:"ohlc",groupPixelWidth:5}},q=a.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]],r={sum:function(c){var a=c.length,f;if(!a&&c.hasNulls)f=null;else if(a)for(f=0;a--;)f+=c[a];return f},average:function(c){var a=c.length;c=r.sum(c);p(c)&&a&&(c/=a);return c},averages:function(){var c=[];w(arguments,function(a){c.push(r.average(a))});
return c},open:function(c){return c.length?c[0]:c.hasNulls?null:void 0},high:function(c){return c.length?F(c):c.hasNulls?null:void 0},low:function(c){return c.length?t(c):c.hasNulls?null:void 0},close:function(c){return c.length?c[c.length-1]:c.hasNulls?null:void 0},ohlc:function(c,a,f,g){c=r.open(c);a=r.high(a);f=r.low(f);g=r.close(g);if(p(c)||p(a)||p(f)||p(g))return[c,a,f,g]},range:function(c,a){c=r.low(c);a=r.high(a);if(p(c)||p(a))return[c,a];if(null===c&&null===a)return null}};h.groupData=function(a,
f,b,e){var c=this.data,l=this.options.data,n=[],x=[],v=[],d=a.length,A,y,h=!!f,k=[];e="function"===typeof e?e:r[e]||D[this.type]&&r[D[this.type].approximation]||r[g.approximation];var q=this.pointArrayMap,G=q&&q.length,m=0;y=0;var P,u;G?w(q,function(){k.push([])}):k.push([]);P=G||1;for(u=0;u<=d&&!(a[u]>=b[0]);u++);for(u;u<=d;u++){for(;void 0!==b[m+1]&&a[u]>=b[m+1]||u===d;){A=b[m];this.dataGroupInfo={start:y,length:k[0].length};y=e.apply(this,k);void 0!==y&&(n.push(A),x.push(y),v.push(this.dataGroupInfo));
y=u;for(A=0;A<P;A++)k[A].length=0,k[A].hasNulls=!1;m+=1;if(u===d)break}if(u===d)break;if(q){A=this.cropStart+u;var t=c&&c[A]||this.pointClass.prototype.applyOptions.apply({series:this},[l[A]]),E;for(A=0;A<G;A++)E=t[q[A]],p(E)?k[A].push(E):null===E&&(k[A].hasNulls=!0)}else A=h?f[u]:null,p(A)?k[0].push(A):null===A&&(k[0].hasNulls=!0)}return[n,x,v]};h.processData=function(){var a=this.chart,f=this.options.dataGrouping,g=!1!==this.allowDG&&f&&J(f.enabled,a.options.isStock),b=this.visible||!a.options.chart.ignoreHiddenSeries,
e;this.forceCrop=g;this.groupPixelWidth=null;this.hasProcessed=!0;if(!1!==k.apply(this,arguments)&&g){this.destroyGroupedData();var l=this.processedXData,n=this.processedYData,x=a.plotSizeX,a=this.xAxis,d=a.options.ordinal,M=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(M){this.isDirty=e=!0;this.points=null;var A=a.getExtremes(),g=A.min,A=A.max,d=d&&a.getGroupIntervalFactor(g,A,this)||1,x=M*(A-g)/x*d,M=a.getTimeTicks(a.normalizeTimeTickInterval(x,f.units||q),Math.min(g,l[0]),
Math.max(A,l[l.length-1]),a.options.startOfWeek,l,this.closestPointRange),l=h.groupData.apply(this,[l,n,M,f.approximation]),n=l[0],d=l[1];if(f.smoothed&&n.length){f=n.length-1;for(n[f]=Math.min(n[f],A);f--&&0<f;)n[f]+=x/2;n[0]=Math.max(n[0],g)}this.currentDataGrouping=M.info;this.closestPointRange=M.info.totalRange;this.groupMap=l[2];E(n[0])&&n[0]<a.dataMin&&b&&(a.min===a.dataMin&&(a.min=n[0]),a.dataMin=n[0]);this.processedXData=n;this.processedYData=d}else this.currentDataGrouping=this.groupMap=
null;this.hasGroupedData=e}};h.destroyGroupedData=function(){var a=this.groupedData;w(a||[],function(c,f){c&&(a[f]=c.destroy?c.destroy():null)});this.groupedData=null};h.generatePoints=function(){m.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};b(e.prototype,"update",function(c){this.dataGroup?a.error(24):c.apply(this,[].slice.call(arguments,1))});b(d.prototype,"tooltipFooterHeaderFormatter",function(c,f,g){var b=f.series,e=b.tooltipOptions,l=b.options.dataGrouping,
n=e.xDateFormat,x,d=b.xAxis,h=a.dateFormat;return d&&"datetime"===d.options.type&&l&&p(f.key)?(c=b.currentDataGrouping,l=l.dateTimeLabelFormats,c?(d=l[c.unitName],1===c.count?n=d[0]:(n=d[1],x=d[2])):!n&&l&&(n=this.getXDateFormat(f,e,d)),n=h(n,f.key),x&&(n+=h(x,f.key+c.totalRange-1)),u(e[(g?"footer":"header")+"Format"],{point:I(f.point,{key:n}),series:b})):c.call(this,f,g)});h.destroy=function(){for(var a=this.groupedData||[],g=a.length;g--;)a[g]&&a[g].destroy();f.apply(this)};b(h,"setOptions",function(a,
f){a=a.call(this,f);var c=this.type,b=this.chart.options.plotOptions,e=B[c].dataGrouping;D[c]&&(e||(e=H(g,D[c])),a.dataGrouping=H(e,b.series&&b.series.dataGrouping,b[c].dataGrouping,f.dataGrouping));this.chart.options.isStock&&(this.requireSorting=!0);return a});b(z.prototype,"setScale",function(a){a.call(this);w(this.series,function(a){a.hasProcessed=!1})});z.prototype.getGroupPixelWidth=function(){var a=this.series,f=a.length,g,b=0,e=!1,l;for(g=f;g--;)(l=a[g].options.dataGrouping)&&(b=Math.max(b,
l.groupPixelWidth));for(g=f;g--;)(l=a[g].options.dataGrouping)&&a[g].hasProcessed&&(f=(a[g].processedXData||a[g].data).length,a[g].groupPixelWidth||f>this.chart.plotSizeX/b||f&&l.forced)&&(e=!0);return e?b:0};z.prototype.setDataGrouping=function(a,f){var c;f=J(f,!0);a||(a={forced:!1,units:null});if(this instanceof z)for(c=this.series.length;c--;)this.series[c].update({dataGrouping:a},!1);else w(this.chart.options.series,function(f){f.dataGrouping=a},!1);f&&this.chart.redraw()}})(K);(function(a){var F=
a.each,t=a.Point,z=a.seriesType,B=a.seriesTypes;z("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eOpen: {point.open}\x3cbr/\x3eHigh: {point.high}\x3cbr/\x3eLow: {point.low}\x3cbr/\x3eClose: {point.close}\x3cbr/\x3e'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(a){return[a.open,a.high,a.low,a.close]},
pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,w){w=B.column.prototype.pointAttribs.call(this,a,w);var t=this.options;delete w.fill;!a.options.color&&t.upColor&&a.open<a.close&&(w.stroke=t.upColor);return w},translate:function(){var a=this,t=a.yAxis,I=!!a.modifyValue,u=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];B.column.prototype.translate.apply(a);F(a.points,function(p){F([p.open,p.high,p.low,p.close,p.low],function(w,z){null!==
w&&(I&&(w=a.modifyValue(w)),p[u[z]]=t.toPixels(w,!0))});p.tooltipPos[1]=p.plotHigh+t.pos-a.chart.plotTop})},drawPoints:function(){var a=this,t=a.chart;F(a.points,function(w){var u,p,H,z,e=w.graphic,d,b=!e;void 0!==w.plotY&&(e||(w.graphic=e=t.renderer.path().add(a.group)),e.attr(a.pointAttribs(w,w.selected&&"select")),p=e.strokeWidth()%2/2,d=Math.round(w.plotX)-p,H=Math.round(w.shapeArgs.width/2),z=["M",d,Math.round(w.yBottom),"L",d,Math.round(w.plotHigh)],null!==w.open&&(u=Math.round(w.plotOpen)+
p,z.push("M",d,u,"L",d-H,u)),null!==w.close&&(u=Math.round(w.plotClose)+p,z.push("M",d,u,"L",d+H,u)),e[b?"attr":"animate"]({d:z}).addClass(w.getClassName(),!0))})},animate:null},{getClassName:function(){return t.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})})(K);(function(a){var F=a.defaultPlotOptions,t=a.each,z=a.merge,B=a.seriesType,E=a.seriesTypes;B("candlestick","ohlc",z(F.column,{states:{hover:{lineWidth:2}},tooltip:F.ohlc.tooltip,
threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(a,t){var u=E.column.prototype.pointAttribs.call(this,a,t),p=this.options,w=a.open<a.close,z=p.lineColor||this.color;u["stroke-width"]=p.lineWidth;u.fill=a.options.color||(w?p.upColor||this.color:this.color);u.stroke=a.lineColor||(w?p.upLineColor||z:z);t&&(a=p.states[t],u.fill=a.color||u.fill,u.stroke=a.lineColor||u.stroke,u["stroke-width"]=a.lineWidth||u["stroke-width"]);return u},drawPoints:function(){var a=
this,z=a.chart;t(a.points,function(u){var p=u.graphic,t,w,e,d,b,h,k,m=!p;void 0!==u.plotY&&(p||(u.graphic=p=z.renderer.path().add(a.group)),p.attr(a.pointAttribs(u,u.selected&&"select")).shadow(a.options.shadow),b=p.strokeWidth()%2/2,h=Math.round(u.plotX)-b,t=u.plotOpen,w=u.plotClose,e=Math.min(t,w),t=Math.max(t,w),k=Math.round(u.shapeArgs.width/2),w=Math.round(e)!==Math.round(u.plotHigh),d=t!==u.yBottom,e=Math.round(e)+b,t=Math.round(t)+b,b=[],b.push("M",h-k,t,"L",h-k,e,"L",h+k,e,"L",h+k,t,"Z","M",
h,e,"L",h,w?Math.round(u.plotHigh):e,"M",h,t,"L",h,d?Math.round(u.yBottom):t),p[m?"attr":"animate"]({d:b}).addClass(u.getClassName(),!0))})}})})(K);(function(a){var F=a.addEvent,t=a.each,z=a.merge,B=a.noop,E=a.Renderer,w=a.seriesType,I=a.seriesTypes,u=a.TrackerMixin,p=a.VMLRenderer,H=a.SVGRenderer.prototype.symbols,J=a.stableSort;w("flags","column",{pointRange:0,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}\x3cbr/\x3e"},threshold:null,y:-30,fillColor:"#ffffff",
lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:a.Series.prototype.init,pointAttribs:function(a,d){var b=this.options,e=a&&a.color||this.color,k=b.lineColor,m=a&&a.lineWidth;a=a&&a.fillColor||b.fillColor;d&&(a=b.states[d].fillColor,k=b.states[d].lineColor,m=b.states[d].lineWidth);return{fill:a||e,stroke:k||e,"stroke-width":m||
b.lineWidth||0}},translate:function(){I.column.prototype.translate.apply(this);var a=this.options,d=this.chart,b=this.points,h=b.length-1,k,m,f=a.onSeries;k=f&&d.get(f);var a=a.onKey||"y",f=k&&k.options.step,g=k&&k.points,D=g&&g.length,q=this.xAxis,r=this.yAxis,c=q.getExtremes(),v=0,y,G,C;if(k&&k.visible&&D)for(v=(k.pointXOffset||0)+(k.barW||0)/2,k=k.currentDataGrouping,G=g[D-1].x+(k?k.totalRange:0),J(b,function(a,n){return a.x-n.x}),a="plot"+a[0].toUpperCase()+a.substr(1);D--&&b[h]&&!(k=b[h],y=g[D],
y.x<=k.x&&void 0!==y[a]&&(k.x<=G&&(k.plotY=y[a],y.x<k.x&&!f&&(C=g[D+1])&&void 0!==C[a]&&(k.plotY+=(k.x-y.x)/(C.x-y.x)*(C[a]-y[a]))),h--,D++,0>h)););t(b,function(a,n){var l;void 0===a.plotY&&(a.x>=c.min&&a.x<=c.max?a.plotY=d.chartHeight-q.bottom-(q.opposite?q.height:0)+q.offset-r.top:a.shapeArgs={});a.plotX+=v;(m=b[n-1])&&m.plotX===a.plotX&&(void 0===m.stackIndex&&(m.stackIndex=0),l=m.stackIndex+1);a.stackIndex=l})},drawPoints:function(){var e=this.points,d=this.chart,b=d.renderer,h,k,m=this.options,
f=m.y,g,D,q,r,c,v,y,G=this.yAxis;for(D=e.length;D--;)q=e[D],y=q.plotX>this.xAxis.len,h=q.plotX,r=q.stackIndex,g=q.options.shape||m.shape,k=q.plotY,void 0!==k&&(k=q.plotY+f-(void 0!==r&&r*m.stackDistance)),c=r?void 0:q.plotX,v=r?void 0:q.plotY,r=q.graphic,void 0!==k&&0<=h&&!y?(r||(r=q.graphic=b.label("",null,null,g,null,null,m.useHTML).attr(this.pointAttribs(q)).css(z(m.style,q.style)).attr({align:"flag"===g?"left":"center",width:m.width,height:m.height,"text-align":m.textAlign}).addClass("highcharts-point").add(this.markerGroup),
q.graphic.div&&(q.graphic.div.point=q),r.shadow(m.shadow)),0<h&&(h-=r.strokeWidth()%2),r.attr({text:q.options.title||m.title||"A",x:h,y:k,anchorX:c,anchorY:v}),q.tooltipPos=d.inverted?[G.len+G.pos-d.plotLeft-k,this.xAxis.len-h]:[h,k+G.pos-d.plotTop]):r&&(q.graphic=r.destroy());m.useHTML&&a.wrap(this.markerGroup,"on",function(f){return a.SVGElement.prototype.on.apply(f.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;u.drawTrackerPoint.apply(this);
t(a,function(d){var b=d.graphic;b&&F(b.element,"mouseover",function(){0<d.stackIndex&&!d.raised&&(d._y=b.y,b.attr({y:d._y-8}),d.raised=!0);t(a,function(a){a!==d&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:B,buildKDTree:B,setClip:B});H.flag=function(a,d,b,h,k){return["M",k&&k.anchorX||a,k&&k.anchorY||d,"L",a,d+h,a,d,a+b,d,a+b,d+h,a,d+h,"Z"]};t(["circle","square"],function(a){H[a+"pin"]=function(d,b,e,k,m){var f=m&&m.anchorX;m=m&&m.anchorY;"circle"===a&&k>e&&(d-=Math.round((k-
e)/2),e=k);d=H[a](d,b,e,k);f&&m&&d.push("M",f,b>m?b:b+k,"L",f,m);return d}});E===p&&t(["flag","circlepin","squarepin"],function(a){p.prototype.symbols[a]=H[a]})})(K);(function(a){function F(a,g,b){this.init(a,g,b)}var t=a.addEvent,z=a.Axis,B=a.correctFloat,E=a.defaultOptions,w=a.defined,I=a.destroyObjectProperties,u=a.each,p=a.fireEvent,H=a.hasTouch,J=a.isTouchDevice,e=a.merge,d=a.pick,b=a.removeEvent,h=a.wrap,k,m={height:J?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:a.svg&&!J,margin:10,
minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};E.scrollbar=e(!0,m,E.scrollbar);a.swapXY=k=function(a,g){var f=a.length,b;if(g)for(g=0;g<f;g+=3)b=a[g+1],a[g+1]=a[g+2],a[g+2]=b;return a};F.prototype={init:function(a,g,b){this.scrollbarButtons=[];
this.renderer=a;this.userOptions=g;this.options=e(m,g);this.chart=b;this.size=d(this.options.size,this.options.height);g.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,g=this.options,b=this.size,d;this.group=d=a.g("scrollbar").attr({zIndex:g.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:g.trackBorderRadius||0,height:b,width:b}).add(d);this.track.attr({fill:g.trackBackgroundColor,stroke:g.trackBorderColor,
"stroke-width":g.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(d);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:b,width:b,r:g.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(k(["M",-3,b/4,"L",-3,2*b/3,"M",0,b/4,"L",0,2*b/3,"M",3,b/4,"L",3,2*b/3],g.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);this.scrollbar.attr({fill:g.barBackgroundColor,
stroke:g.barBorderColor,"stroke-width":g.barBorderWidth});this.scrollbarRifles.attr({stroke:g.rifleColor,"stroke-width":1});this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,g,b,d){var f=this.options.vertical,c=0,e=this.rendered?"animate":"attr";this.x=a;this.y=g+this.trackBorderWidth;this.width=b;this.xOffset=this.height=d;
this.yOffset=c;f?(this.width=this.yOffset=b=c=this.size,this.xOffset=g=0,this.barWidth=d-2*b,this.x=a+=this.options.margin):(this.height=this.xOffset=d=g=this.size,this.barWidth=b-2*d,this.y+=this.options.margin);this.group[e]({translateX:a,translateY:this.y});this.track[e]({width:b,height:d});this.scrollbarButtons[1][e]({translateX:f?0:b-g,translateY:f?d-c:0})},drawScrollbarButton:function(a){var f=this.renderer,b=this.scrollbarButtons,d=this.options,e=this.size,c;c=f.g().add(this.group);b.push(c);
c=f.rect().addClass("highcharts-scrollbar-button").add(c);c.attr({stroke:d.buttonBorderColor,"stroke-width":d.buttonBorderWidth,fill:d.buttonBackgroundColor});c.attr(c.crisp({x:-.5,y:-.5,width:e+1,height:e+1,r:d.buttonBorderRadius},c.strokeWidth()));c=f.path(k(["M",e/2+(a?-1:1),e/2-3,"L",e/2+(a?-1:1),e/2+3,"L",e/2+(a?2:-2),e/2],d.vertical)).addClass("highcharts-scrollbar-arrow").add(b[a]);c.attr({fill:d.buttonArrowColor})},setRange:function(a,g){var f=this.options,b=f.vertical,d=f.minWidth,c=this.barWidth,
e,h,k=this.rendered&&!this.hasDragged?"animate":"attr";w(c)&&(a=Math.max(a,0),e=Math.ceil(c*a),this.calculatedWidth=h=B(c*Math.min(g,1)-e),h<d&&(e=(c-d+h)*a,h=d),d=Math.floor(e+this.xOffset+this.yOffset),c=h/2-.5,this.from=a,this.to=g,b?(this.scrollbarGroup[k]({translateY:d}),this.scrollbar[k]({height:h}),this.scrollbarRifles[k]({translateY:c}),this.scrollbarTop=d,this.scrollbarLeft=0):(this.scrollbarGroup[k]({translateX:d}),this.scrollbar[k]({width:h}),this.scrollbarRifles[k]({translateX:c}),this.scrollbarLeft=
d,this.scrollbarTop=0),12>=h?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0),!1===f.showFull&&(0>=a&&1<=g?this.group.hide():this.group.show()),this.rendered=!0)},initEvents:function(){var a=this;a.mouseMoveHandler=function(g){var b=a.chart.pointer.normalize(g),d=a.options.vertical?"chartY":"chartX",f=a.initPositions;!a.grabbedCenter||g.touches&&0===g.touches[0][d]||(b=a.cursorToScrollbarPosition(b)[d],d=a[d],d=b-d,a.hasDragged=!0,a.updatePosition(f[0]+d,f[1]+d),a.hasDragged&&p(a,"changed",
{from:a.from,to:a.to,trigger:"scrollbar",DOMType:g.type,DOMEvent:g}))};a.mouseUpHandler=function(b){a.hasDragged&&p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(b){b=a.chart.pointer.normalize(b);b=a.cursorToScrollbarPosition(b);a.chartX=b.chartX;a.chartY=b.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(b){var g=B(a.to-a.from)*a.options.step;a.updatePosition(B(a.from-
g),B(a.to-g));p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.buttonToMaxClick=function(b){var g=(a.to-a.from)*a.options.step;a.updatePosition(a.from+g,a.to+g);p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.trackClick=function(b){var g=a.chart.pointer.normalize(b),d=a.to-a.from,f=a.y+a.scrollbarTop,c=a.x+a.scrollbarLeft;a.options.vertical&&g.chartY>f||!a.options.vertical&&g.chartX>c?a.updatePosition(a.from+d,a.to+d):a.updatePosition(a.from-d,a.to-d);
p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})}},cursorToScrollbarPosition:function(a){var b=this.options,b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}},updatePosition:function(a,b){1<b&&(a=B(1-B(b-a)),b=1);0>a&&(b=B(b-a),a=0);this.from=a;this.to=b},update:function(a){this.destroy();this.init(this.chart.renderer,e(!0,this.options,a),this.chart)},addEvents:function(){var a=
this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,d=this.scrollbarGroup.element,e=this.mouseDownHandler,h=this.mouseMoveHandler,c=this.mouseUpHandler,a=[[b[a[0]].element,"click",this.buttonToMinClick],[b[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[d,"mousedown",e],[d.ownerDocument,"mousemove",h],[d.ownerDocument,"mouseup",c]];H&&a.push([d,"touchstart",e],[d.ownerDocument,"touchmove",h],[d.ownerDocument,"touchend",c]);u(a,function(a){t.apply(null,
a)});this._events=a},removeEvents:function(){u(this._events,function(a){b.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();u(["track","scrollbarRifles","scrollbar","scrollbarGroup","group"],function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,I(a.scrollbarButtons))}};h(z.prototype,"init",function(a){var b=this;a.apply(b,Array.prototype.slice.call(arguments,1));b.options.scrollbar&&b.options.scrollbar.enabled&&
(b.options.scrollbar.vertical=!b.horiz,b.options.startOnTick=b.options.endOnTick=!1,b.scrollbar=new F(b.chart.renderer,b.options.scrollbar,b.chart),t(b.scrollbar,"changed",function(a){var e=Math.min(d(b.options.min,b.min),b.min,b.dataMin),g=Math.max(d(b.options.max,b.max),b.max,b.dataMax)-e,c;b.horiz&&!b.reversed||!b.horiz&&b.reversed?(c=e+g*this.to,e+=g*this.from):(c=e+g*(1-this.from),e+=g*(1-this.to));b.setExtremes(e,c,!0,!1,a)}))});h(z.prototype,"render",function(a){var b=Math.min(d(this.options.min,
this.min),this.min,d(this.dataMin,this.min)),e=Math.max(d(this.options.max,this.max),this.max,d(this.dataMax,this.max)),h=this.scrollbar,f=this.titleOffset||0;a.apply(this,Array.prototype.slice.call(arguments,1));if(h){this.horiz?(h.position(this.left,this.top+this.height+2+this.chart.scrollbarsOffsets[1]+(this.opposite?0:f+this.axisTitleMargin+this.offset),this.width,this.height),f=1):(h.position(this.left+this.width+2+this.chart.scrollbarsOffsets[0]+(this.opposite?f+this.axisTitleMargin+this.offset:
0),this.top,this.width,this.height),f=0);if(!this.opposite&&!this.horiz||this.opposite&&this.horiz)this.chart.scrollbarsOffsets[f]+=this.scrollbar.size+this.scrollbar.options.margin;isNaN(b)||isNaN(e)||!w(this.min)||!w(this.max)?h.setRange(0,0):(f=(this.min-b)/(e-b),b=(this.max-b)/(e-b),this.horiz&&!this.reversed||!this.horiz&&this.reversed?h.setRange(f,b):h.setRange(1-b,1-f))}});h(z.prototype,"getOffset",function(a){var b=this.horiz?2:1,d=this.scrollbar;a.apply(this,Array.prototype.slice.call(arguments,
1));d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=d.size+d.options.margin)});h(z.prototype,"destroy",function(a){this.scrollbar&&(this.scrollbar=this.scrollbar.destroy());a.apply(this,Array.prototype.slice.call(arguments,1))});a.Scrollbar=F})(K);(function(a){function F(a){this.init(a)}var t=a.addEvent,z=a.Axis,B=a.Chart,E=a.color,w=a.defaultOptions,I=a.defined,u=a.destroyObjectProperties,p=a.each,H=a.erase,J=a.error,e=a.extend,d=a.grep,b=a.hasTouch,h=a.isArray,k=a.isNumber,m=a.isObject,
f=a.merge,g=a.pick,D=a.removeEvent,q=a.Scrollbar,r=a.Series,c=a.seriesTypes,v=a.wrap,y=a.swapXY,G=[].concat(a.defaultDataGroupingUnits),C=function(a){var l=d(arguments,k);if(l.length)return Math[a].apply(0,l)};G[4]=["day",[1,2,3,4]];G[5]=["week",[1,2,3]];c=void 0===c.areaspline?"line":"areaspline";e(w,{navigator:{height:40,margin:25,maskInside:!0,handles:{backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:E("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:c,
color:"#335cad",fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:G},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},pointRange:0,threshold:null},xAxis:{className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},
crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});F.prototype={drawHandle:function(a,b,c,d){this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2-8),translateY:Math.round(this.top+parseInt(a,10)+.5)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-8)})},getHandlePath:function(a){return y(["M",
-4.5,.5,"L",3.5,.5,"L",3.5,15.5,"L",-4.5,15.5,"L",-4.5,.5,"M",-1.5,4,"L",-1.5,12,"M",.5,4,"L",.5,12],a)},drawOutline:function(a,b,c,d){var l=this.navigatorOptions.maskInside,n=this.outline.strokeWidth(),x=n/2,n=n%2/2,e=this.outlineHeight,g=this.scrollbarHeight,h=this.size,f=this.left-g,k=this.top;c?(f-=x,c=k+b+n,b=k+a+n,a=["M",f+e,k-g-n,"L",f+e,c,"L",f,c,"L",f,b,"L",f+e,b,"L",f+e,k+h+g].concat(l?["M",f+e,c-x,"L",f+e,b+x]:[])):(a+=f+g-n,b+=f+g-n,k+=x,a=["M",f,k,"L",a,k,"L",a,k+e,"L",b,k+e,"L",b,k,
"L",f+h+2*g,k].concat(l?["M",a-x,k,"L",b+x,k]:[]));this.outline[d]({d:a})},drawMasks:function(a,b,c,d){var l=this.left,n=this.top,x=this.height,e,g,f,h;c?(f=[l,l,l],h=[n,n+a,n+b],g=[x,x,x],e=[a,b-a,this.size-b]):(f=[l,l+a,l+b],h=[n,n,n],g=[a,b-a,this.size-b],e=[x,x,x]);p(this.shades,function(a,b){a[d]({x:f[b],y:h[b],width:g[b],height:e[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.inverted,g=d.renderer,f;a.navigatorGroup=f=g.g("navigator").attr({zIndex:8,
visibility:"hidden"}).add();var h={cursor:e?"ns-resize":"ew-resize"};p([!c,c,!c],function(l,c){a.shades[c]=g.rect().addClass("highcharts-navigator-mask"+(1===c?"-inside":"-outside")).attr({fill:l?b.maskFill:"rgba(0,0,0,0)"}).css(1===c&&h).add(f)});a.outline=g.path().addClass("highcharts-navigator-outline").attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor}).add(f);p([0,1],function(l){a.handles[l]=g.path(a.getHandlePath(e)).attr({zIndex:7-l}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+
["left","right"][l]).add(f);var c=b.handles;a.handles[l].attr({fill:c.backgroundColor,stroke:c.borderColor,"stroke-width":1}).css(h)})},update:function(a){p(this.series||[],function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();f(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(a,b,c,d){var l=this.chart,n,e,x=this.scrollbarHeight,f,h=this.xAxis;n=h.fake?l.xAxis[0]:h;var C=this.navigatorEnabled,L,y=this.rendered;e=l.inverted;var v=l.xAxis[0].minRange;
if(!this.hasDragged||I(c)){if(!k(a)||!k(b))if(y)c=0,d=h.width;else return;this.left=g(h.left,l.plotLeft+x+(e?l.plotWidth:0));this.size=L=f=g(h.len,(e?l.plotHeight:l.plotWidth)-2*x);l=e?x:f+2*x;c=g(c,h.toPixels(a,!0));d=g(d,h.toPixels(b,!0));k(c)&&Infinity!==Math.abs(c)||(c=0,d=l);a=h.toValue(c,!0);b=h.toValue(d,!0);if(Math.abs(b-a)<v)if(this.grabbedLeft)c=h.toPixels(b-v,!0);else if(this.grabbedRight)d=h.toPixels(a+v,!0);else return;this.zoomedMax=Math.min(Math.max(c,d,0),L);this.zoomedMin=Math.min(Math.max(this.fixedWidth?
this.zoomedMax-this.fixedWidth:Math.min(c,d),0),L);this.range=this.zoomedMax-this.zoomedMin;L=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);C&&(this.navigatorGroup.attr({visibility:"visible"}),y=y&&!this.hasDragged?"animate":"attr",this.drawMasks(c,L,e,y),this.drawOutline(c,L,e,y),this.drawHandle(c,0,e,y),this.drawHandle(L,1,e,y));this.scrollbar&&(e?(e=this.top-x,n=this.left-x+(C||!n.opposite?0:(n.titleOffset||0)+n.axisTitleMargin),x=f+2*x):(e=this.top+(C?this.height:-x),n=this.left-x),
this.scrollbar.position(n,e,l,x),this.scrollbar.setRange(this.zoomedMin/f,this.zoomedMax/f));this.rendered=!0}},addMouseEvents:function(){var a=this,c=a.chart,d=c.container,e=[],f,g;a.mouseMoveHandler=f=function(b){a.onMouseMove(b)};a.mouseUpHandler=g=function(b){a.onMouseUp(b)};e=a.getPartsEvents("mousedown");e.push(t(d,"mousemove",f),t(d.ownerDocument,"mouseup",g));b&&(e.push(t(d,"touchmove",f),t(d.ownerDocument,"touchend",g)),e.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=e;a.series&&
a.series[0]&&e.push(t(a.series[0].xAxis,"foundExtremes",function(){c.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=this,l=[];p(["shades","handles"],function(c){p(b[c],function(n,d){l.push(t(n.element,a,function(a){b[c+"Mousedown"](a,d)}))})});return l},shadesMousedown:function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,l=this.xAxis,d=this.zoomedMin,n=this.left,e=this.size,f=this.range,g=a.chartX,h;c.inverted&&(g=a.chartY,n=this.top);1===b?(this.grabbedCenter=
g,this.fixedWidth=f,this.dragOffset=g-d):(a=g-n-f/2,0===b?a=Math.max(0,a):2===b&&a+f>=e&&(a=e-f,h=this.getUnionExtremes().dataMax),a!==d&&(this.fixedWidth=f,b=l.toFixedRange(a,a+f,null,h),c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"})))},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],l=a.inverted&&!c.reversed||!a.inverted&&c.reversed;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=
l?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=l?c.max:c.min);a.fixedRange=null},onMouseMove:function(a){var b=this,c=b.chart,l=b.left,d=b.navigatorSize,e=b.range,f=b.dragOffset,g=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,g&&(l=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-l,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-l)):b.grabbedCenter&&(b.hasDragged=!0,c<
f?c=f:c>d+f-e&&(c=d+f-e),b.render(0,0,c-f,c-f+e)),b.hasDragged&&b.scrollbar&&b.scrollbar.options.liveRedraw&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,c=this.xAxis,l=this.scrollbar,d,e,f=a.DOMEvent||a;(!this.hasDragged||l&&l.hasDragged)&&"scrollbar"!==a.trigger||(this.zoomedMin===this.otherHandlePos?d=this.fixedExtreme:this.zoomedMax===this.otherHandlePos&&(e=this.fixedExtreme),this.zoomedMax===this.size&&(e=this.getUnionExtremes().dataMax),
c=c.toFixedRange(this.zoomedMin,this.zoomedMax,d,e),I(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:f}));"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(p(this.eventsToUnbind,function(a){a()}),this.eventsToUnbind=void 0);
this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&p(a,function(a){D(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&D(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var b=a.options,c=b.navigator,d=c.enabled,l=b.scrollbar,e=l.enabled,b=d?c.height:0,h=e?l.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=
h;this.scrollbarEnabled=e;this.navigatorEnabled=d;this.navigatorOptions=c;this.scrollbarOptions=l;this.outlineHeight=b+h;this.opposite=g(c.opposite,!d&&a.inverted);var k=this,l=k.baseSeries,e=a.xAxis.length,y=a.yAxis.length,G=l&&l[0]&&l[0].xAxis||a.xAxis[0];a.extraMargin={type:k.opposite?"plotTop":"marginBottom",value:(d||!a.inverted?k.outlineHeight:0)+c.margin};a.inverted&&(a.extraMargin.type=k.opposite?"marginRight":"plotLeft");a.isDirtyBox=!0;k.navigatorEnabled?(k.xAxis=new z(a,f({breaks:G.options.breaks,
ordinal:G.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[h,0,-h,0],width:b}:{offsets:[0,-h,0,h],height:b})),k.yAxis=new z(a,f(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:y,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),l||c.series.data?k.updateNavigatorSeries():0===a.series.length&&v(a,"redraw",function(b,
c){0<a.series.length&&!k.series&&(k.setBaseSeries(),a.redraw=b);b.call(a,c)}),k.renderElements(),k.addMouseEvents()):k.xAxis={translate:function(b,c){var d=a.xAxis[0],l=d.getExtremes(),e=d.len-2*h,n=C("min",d.options.min,l.dataMin),d=C("max",d.options.max,l.dataMax)-n;return c?b*d/e+n:e*(b-n)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:z.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=k.scrollbar=new q(a.renderer,
f(a.options.scrollbar,{margin:k.navigatorEnabled?0:10,vertical:a.inverted}),a),t(k.scrollbar,"changed",function(b){var c=k.size,d=c*this.to,c=c*this.from;k.hasDragged=k.scrollbar.hasDragged;k.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType)&&setTimeout(function(){k.onMouseUp(b)})}));k.addBaseSeriesEvents();k.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,l=b.options,e;a&&null===b.dataMin||(e={dataMin:g(d&&d.min,C("min",l.min,
b.dataMin,c.dataMin,c.min)),dataMax:g(d&&d.max,C("max",l.max,b.dataMax,c.dataMax,c.max))});return e},setBaseSeries:function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||0;p(c.series||[],function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(b)},updateNavigatorSeries:function(b){var c=this,d=c.chart,l=c.baseSeries,e,g,
k=c.navigatorOptions.series,C,y={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,visible:!0},v=c.series=a.grep(c.series||[],function(b){var d=b.baseSeries;return 0>a.inArray(d,l)?(d&&(D(d,"updatedData",c.updatedDataHandler),delete d.navigatorSeries),b.destroy(),!1):!0});l&&l.length&&p(l,function(a){var n=a.navigatorSeries,x=h(k)?w.navigator.series:k;n&&!1===c.navigatorOptions.adaptToUpdatedData||
(y.name="Navigator "+l.length,e=a.options||{},C=e.navigatorOptions||{},g=f(e,y,x,C),x=C.data||x.data,c.hasNavigatorData=c.hasNavigatorData||!!x,g.data=x||e.data&&e.data.slice(0),n?n.update(g,b):(a.navigatorSeries=d.initSeries(g),a.navigatorSeries.baseSeries=a,v.push(a.navigatorSeries)))});if(k.data&&(!l||!l.length)||h(k))c.hasNavigatorData=!1,k=a.splat(k),p(k,function(a,b){y.name="Navigator "+(v.length+1);g=f(w.navigator.series,{color:d.series[b]&&!d.series[b].options.isInternal&&d.series[b].color||
d.options.colors[b]||d.options.colors[0]},y,a);g.data=a.data;g.data&&(c.hasNavigatorData=!0,v.push(d.initSeries(g)))});this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&t(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);p(b,function(b){t(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.show()});t(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.hide()});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&
t(b,"updatedData",this.updatedDataHandler);t(b,"remove",function(){this.navigatorSeries&&(H(a.series,this.navigatorSeries),this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax,b=b.max-b.min,e=a.stickToMin,
f=a.stickToMax,g,h,C=a.series&&a.series[0],y=!!this.setExtremes;this.eventArgs&&"rangeSelectorButton"===this.eventArgs.trigger||(e&&(h=c,g=h+b),f&&(g=d,e||(h=Math.max(g-b,C&&C.xData?C.xData[0]:-Number.MAX_VALUE))),y&&(e||f)&&k(h)&&(this.min=this.userMin=h,this.max=this.userMax=g));a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries;a.stickToMax=Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=k(this.xAxis.min)&&this.xAxis.min<=this.xData[0]&&
(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){t(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)})},destroy:function(){this.removeEvents();this.xAxis&&(H(this.chart.xAxis,this.xAxis),H(this.chart.axes,this.xAxis));this.yAxis&&(H(this.chart.yAxis,this.yAxis),H(this.chart.axes,
this.yAxis));p(this.series||[],function(a){a.destroy&&a.destroy()});p("series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" "),function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);p([this.handles],function(a){u(a)},this)}};a.Navigator=F;v(z.prototype,"zoom",function(a,b,c){var d=this.chart,e=d.options,l=e.chart.zoomType,g=e.navigator,e=e.rangeSelector,f;this.isXAxis&&(g&&g.enabled||e&&e.enabled)&&("x"===l?
d.resetZoomButton="blocked":"y"===l?f=!1:"xy"===l&&(d=this.previousZoom,I(b)?this.previousZoom=[this.min,this.max]:d&&(b=d[0],c=d[1],delete this.previousZoom)));return void 0!==f?f:a.call(this,b,c)});v(B.prototype,"init",function(a,b,c){t(this,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new F(this)});a.call(this,b,c)});v(B.prototype,"setChartSize",function(a){var b=this.legend,c=this.navigator,d,e,l,f;a.apply(this,[].slice.call(arguments,
1));c&&(e=b.options,l=c.xAxis,f=c.yAxis,d=c.scrollbarHeight,this.inverted?(c.left=c.opposite?this.chartWidth-d-c.height:this.spacing[3]+d,c.top=this.plotTop+d):(c.left=this.plotLeft+d,c.top=c.navigatorOptions.top||this.chartHeight-c.height-d-this.spacing[2]-("bottom"===e.verticalAlign&&e.enabled&&!e.floating?b.legendHeight+g(e.margin,10):0)),l&&f&&(this.inverted?l.options.left=f.options.left=c.left:l.options.top=f.options.top=c.top,l.setAxisSize(),f.setAxisSize()))});v(r.prototype,"addPoint",function(a,
b,c,d,e){var l=this.options.turboThreshold;l&&this.xData.length>l&&m(b,!0)&&this.chart.navigator&&J(20,!0);a.call(this,b,c,d,e)});v(B.prototype,"addSeries",function(a,b,c,d){a=a.call(this,b,!1,d);this.navigator&&this.navigator.setBaseSeries(null,!1);g(c,!0)&&this.redraw();return a});v(r.prototype,"update",function(a,b,c){a.call(this,b,!1);this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1);g(c,!0)&&this.chart.redraw()});B.prototype.callbacks.push(function(a){var b=
a.navigator;b&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))})})(K);(function(a){function F(a){this.init(a)}var t=a.addEvent,z=a.Axis,B=a.Chart,E=a.css,w=a.createElement,I=a.dateFormat,u=a.defaultOptions,p=u.global.useUTC,H=a.defined,J=a.destroyObjectProperties,e=a.discardElement,d=a.each,b=a.extend,h=a.fireEvent,k=a.Date,m=a.isNumber,f=a.merge,g=a.pick,D=a.pInt,q=a.splat,r=a.wrap;b(u,{rangeSelector:{buttonTheme:{"stroke-width":0,width:28,height:18,padding:2,zIndex:7},height:35,inputPosition:{align:"right"},
labelStyle:{color:"#666666"}}});u.lang=f(u.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});F.prototype={clickButton:function(a,b){var c=this,e=c.chart,f=c.buttonOptions[a],l=e.xAxis[0],h=e.scroller&&e.scroller.getUnionExtremes()||l||{},k=h.dataMin,v=h.dataMax,u,A=l&&Math.round(Math.min(l.max,g(v,l.max))),r=f.type,w,h=f._range,N,O,B,E=f.dataGrouping;if(null!==k&&null!==v){e.fixedRange=h;E&&(this.forcedDataGrouping=!0,z.prototype.setDataGrouping.call(l||{chart:this.chart},
E,!1));if("month"===r||"year"===r)l?(r={range:f,max:A,dataMin:k,dataMax:v},u=l.minFromRange.call(r),m(r.newMax)&&(A=r.newMax)):h=f;else if(h)u=Math.max(A-h,k),A=Math.min(u+h,v);else if("ytd"===r)if(l)void 0===v&&(k=Number.MAX_VALUE,v=Number.MIN_VALUE,d(e.series,function(a){a=a.xData;k=Math.min(a[0],k);v=Math.max(a[a.length-1],v)}),b=!1),A=c.getYTDExtremes(v,k,p),u=N=A.min,A=A.max;else{t(e,"beforeRender",function(){c.clickButton(a)});return}else"all"===r&&l&&(u=k,A=v);c.setSelected(a);l?l.setExtremes(u,
A,g(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:f}):(w=q(e.options.xAxis)[0],B=w.range,w.range=h,O=w.min,w.min=N,t(e,"load",function(){w.range=B;w.min=O}))}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,c=a.options.rangeSelector,e=c.buttons||
[].concat(b.defaultButtons),f=c.selected,l=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&h(a,"blur");c&&c.blur&&h(c,"blur")};b.chart=a;b.options=c;b.buttons=[];a.extraTopMargin=c.height;b.buttonOptions=e;this.unMouseDown=t(a.container,"mousedown",l);this.unResize=t(a,"resize",l);d(e,b.computeButtonRange);void 0!==f&&e[f]&&this.clickButton(f,!1);t(a,"load",function(){t(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&
b.forcedDataGrouping&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this.chart,b=a.xAxis[0],e=Math.round(b.max-b.min),f=!b.hasVisibleSeries,a=a.scroller&&a.scroller.getUnionExtremes()||b,g=a.dataMin,l=a.dataMax,a=this.getYTDExtremes(l,g,p),h=a.min,k=a.max,u=this.selected,t=m(u),A=this.options.allButtonsEnabled,r=this.buttons;d(this.buttonOptions,function(a,c){var d=a._range,n=a.type,C=a.count||1;a=r[c];var y=0;c=c===u;var v=d>l-g,x=d<b.minRange,m=!1,G=!1,d=d===e;("month"===
n||"year"===n)&&e>=864E5*{month:28,year:365}[n]*C&&e<=864E5*{month:31,year:366}[n]*C?d=!0:"ytd"===n?(d=k-h===e,m=!c):"all"===n&&(d=b.max-b.min>=l-g,G=!c&&t&&d);n=!A&&(v||x||G||f);d=c&&d||d&&!t&&!m;n?y=3:d&&(t=!0,y=2);a.state!==y&&a.setState(y)})},computeButtonRange:function(a){var b=a.type,c=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[b])a._range=d[b]*c;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*c},setInputValue:function(a,b){var c=
this.chart.options.rangeSelector,d=this[a+"Input"];H(b)&&(d.previousValue=d.HCTime,d.HCTime=b);d.value=I(c.inputEditDateFormat||"%Y-%m-%d",d.HCTime);this[a+"DateBox"].attr({text:I(c.inputDateFormat||"%b %e, %Y",d.HCTime)})},showInput:function(a){var b=this.inputGroup,c=this[a+"DateBox"];E(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){E(this[a+"Input"],{border:0,width:"1px",height:"1px"});
this.setInputValue(a)},drawInput:function(a){function c(){var a=r.value,b=(h.inputDateParser||Date.parse)(a),c=e.xAxis[0],f=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:c,g=f.dataMin,f=f.dataMax;b!==r.previousValue&&(r.previousValue=b,m(b)||(b=a.split("-"),b=Date.UTC(D(b[0]),D(b[1])-1,D(b[2]))),m(b)&&(p||(b+=6E4*(new Date).getTimezoneOffset()),t?b>d.maxInput.HCTime?b=void 0:b<g&&(b=g):b<d.minInput.HCTime?b=void 0:b>f&&(b=f),void 0!==b&&c.setExtremes(t?b:c.min,t?c.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}
var d=this,e=d.chart,g=e.renderer.style||{},l=e.renderer,h=e.options.rangeSelector,k=d.div,t="min"===a,r,A,q=this.inputGroup;this[a+"Label"]=A=l.label(u.lang[t?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(q);q.offset+=A.width+5;this[a+"DateBox"]=l=l.label("",q.offset).addClass("highcharts-range-input").attr({padding:2,width:h.inputBoxWidth||90,height:h.inputBoxHeight||17,stroke:h.inputBoxBorderColor||"#cccccc","stroke-width":1,
"text-align":"center"}).on("click",function(){d.showInput(a);d[a+"Input"].focus()}).add(q);q.offset+=l.width+(t?10:0);this[a+"Input"]=r=w("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},k);A.css(f(g,h.labelStyle));l.css(f({color:"#333333"},g,h.inputStyle));E(r,b({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:g.fontSize,fontFamily:g.fontFamily,left:"-9em"},h.inputStyle));r.onfocus=function(){d.showInput(a)};r.onblur=
function(){d.hideInput(a)};r.onchange=c;r.onkeypress=function(a){13===a.keyCode&&c()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector,a=g((b.buttonPosition||{}).y,a.plotTop-a.axisOffset[0]-b.height);return{buttonTop:a,inputTop:a-10}},getYTDExtremes:function(a,b,d){var c=new k(a),e=c[k.hcGetFullYear]();d=d?k.UTC(e,0,1):+new k(e,0,1);b=Math.max(b||0,d);c=c.getTime();return{max:Math.min(a||c,c),min:b}},render:function(a,e){var c=this,f=c.chart,h=f.renderer,l=f.container,k=f.options,
x=k.exporting&&!1!==k.exporting.enabled&&k.navigation&&k.navigation.buttonOptions,v=k.rangeSelector,m=c.buttons,k=u.lang,A=c.div,A=c.inputGroup,t=v.buttonTheme,r=v.buttonPosition||{},q=v.inputEnabled,p=t&&t.states,z=f.plotLeft,B,E=this.getPosition(),D=c.group,F=c.rendered;!1!==v.enabled&&(F||(c.group=D=h.g("range-selector-buttons").add(),c.zoomText=h.text(k.rangeSelectorZoom,g(r.x,z),15).css(v.labelStyle).add(D),B=g(r.x,z)+c.zoomText.getBBox().width+5,d(c.buttonOptions,function(a,b){m[b]=h.button(a.text,
B,0,function(){c.clickButton(b);c.isActive=!0},t,p&&p.hover,p&&p.select,p&&p.disabled).attr({"text-align":"center"}).add(D);B+=m[b].width+g(v.buttonSpacing,5)}),!1!==q&&(c.div=A=w("div",null,{position:"relative",height:0,zIndex:1}),l.parentNode.insertBefore(A,l),c.inputGroup=A=h.g("input-group").add(),A.offset=0,c.drawInput("min"),c.drawInput("max"))),c.updateButtonStates(),D[F?"animate":"attr"]({translateY:E.buttonTop}),!1!==q&&(A.align(b({y:E.inputTop,width:A.offset,x:x&&E.inputTop<(x.y||0)+x.height-
f.spacing[0]?-40:0},v.inputPosition),!0,f.spacingBox),H(q)||(f=D.getBBox(),A[A.alignAttr.translateX<f.x+f.width+10?"hide":"show"]()),c.setInputValue("min",a),c.setInputValue("max",e)),c.rendered=!0)},update:function(a){var b=this.chart;f(!0,b.options.rangeSelector,a);this.destroy();this.init(b)},destroy:function(){var b=this,d=b.minInput,f=b.maxInput;b.unMouseDown();b.unResize();J(b.buttons);d&&(d.onfocus=d.onblur=d.onchange=null);f&&(f.onfocus=f.onblur=f.onchange=null);a.objectEach(b,function(a,
c){a&&"chart"!==c&&(a.destroy?a.destroy():a.nodeType&&e(this[c]));a!==F.prototype[c]&&(b[c]=null)},this)}};z.prototype.toFixedRange=function(a,b,d,e){var c=this.chart&&this.chart.fixedRange;a=g(d,this.translate(a,!0,!this.horiz));b=g(e,this.translate(b,!0,!this.horiz));d=c&&(b-a)/c;.7<d&&1.3>d&&(e?a=b-c:b=a+c);m(a)||(a=b=void 0);return{min:a,max:b}};z.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],d,e=this.max,f,h,k=function(a,c){var d=new Date(a),e=d["get"+
b]();d["set"+b](e+c);e===d["get"+b]()&&d.setDate(0);return d.getTime()-a};m(a)?(d=e-a,h=a):(d=e+k(e,-a.count),this.chart&&(this.chart.fixedRange=e-d));f=g(this.dataMin,Number.MIN_VALUE);m(d)||(d=f);d<=f&&(d=f,void 0===h&&(h=k(d,a.count)),this.newMax=Math.min(d+h,this.dataMax));m(e)||(d=void 0);return d};r(B.prototype,"init",function(a,b,d){t(this,"init",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new F(this))});a.call(this,b,d)});B.prototype.callbacks.push(function(a){function b(){c=
a.xAxis[0].getExtremes();m(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector,e,f;d&&(f=t(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)}),e=t(a,"redraw",b),b());t(a,"destroy",function(){d&&(e(),f())})});a.RangeSelector=F})(K);(function(a){var F=a.arrayMax,t=a.arrayMin,z=a.Axis,B=a.Chart,E=a.defined,w=a.each,I=a.extend,u=a.format,p=a.grep,H=a.inArray,J=a.isNumber,e=a.isString,d=a.map,b=a.merge,h=a.pick,k=a.Point,m=a.Renderer,f=a.Series,g=a.splat,D=a.SVGRenderer,q=a.VMLRenderer,
r=a.wrap,c=f.prototype,v=c.init,y=c.processData,G=k.prototype.tooltipFormatter;a.StockChart=a.stockChart=function(c,f,k){var l=e(c)||c.nodeName,n=arguments[l?1:0],C=n.series,m=a.getOptions(),t,r=h(n.navigator&&n.navigator.enabled,m.navigator.enabled,!0),p=r?{startOnTick:!1,endOnTick:!1}:null,q={marker:{enabled:!1,radius:2}},u={shadow:!1,borderWidth:0};n.xAxis=d(g(n.xAxis||{}),function(a){return b({minPadding:0,maxPadding:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},
m.xAxis,a,{type:"datetime",categories:null},p)});n.yAxis=d(g(n.yAxis||{}),function(a){t=h(a.opposite,!0);return b({labels:{y:-2},opposite:t,showLastLabel:!1,title:{text:null}},m.yAxis,a)});n.series=null;n=b({chart:{panning:!0,pinchType:"x"},navigator:{enabled:r},scrollbar:{enabled:h(m.scrollbar.enabled,!0)},rangeSelector:{enabled:h(m.rangeSelector.enabled,!0)},title:{text:null},tooltip:{shared:!0,crosshairs:!0},legend:{enabled:!1},plotOptions:{line:q,spline:q,area:q,areaspline:q,arearange:q,areasplinerange:q,
column:u,columnrange:u,candlestick:u,ohlc:u}},n,{isStock:!0});n.series=C;return l?new B(c,n,k):new B(n,f)};r(z.prototype,"autoLabelAlign",function(a){var b=this.chart,c=this.options,b=b._labelPanes=b._labelPanes||{},d=this.options.labels;return this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled)?(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,"right"):a.apply(this,[].slice.call(arguments,1))});r(z.prototype,"destroy",function(a){var b=this.chart,
c=this.options&&this.options.top+","+this.options.height;c&&b._labelPanes&&b._labelPanes[c]===this&&delete b._labelPanes[c];return a.apply(this,Array.prototype.slice.call(arguments,1))});r(z.prototype,"getPlotLinePath",function(b,c,f,g,k,m){var l=this,n=this.isLinked&&!this.series?this.linkedParent.series:this.series,C=l.chart,t=C.renderer,r=l.left,q=l.top,x,p,u,v,y=[],z=[],B,D;if("xAxis"!==l.coll&&"yAxis"!==l.coll)return b.apply(this,[].slice.call(arguments,1));z=function(a){var b="xAxis"===a?"yAxis":
"xAxis";a=l.options[b];return J(a)?[C[b][a]]:e(a)?[C.get(a)]:d(n,function(a){return a[b]})}(l.coll);w(l.isXAxis?C.yAxis:C.xAxis,function(a){if(E(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis",b=E(a.options[b])?C[b][a.options[b]]:C[b][0];l===b&&z.push(a)}});B=z.length?[]:[l.isXAxis?C.yAxis[0]:C.xAxis[0]];w(z,function(b){-1!==H(b,B)||a.find(B,function(a){return a.pos===b.pos&&a.len&&b.len})||B.push(b)});D=h(m,l.translate(c,null,null,g));J(D)&&(l.horiz?w(B,function(a){var b;
p=a.pos;v=p+a.len;x=u=Math.round(D+l.transB);if(x<r||x>r+l.width)k?x=u=Math.min(Math.max(r,x),r+l.width):b=!0;b||y.push("M",x,p,"L",u,v)}):w(B,function(a){var b;x=a.pos;u=x+a.len;p=v=Math.round(q+l.height-D);if(p<q||p>q+l.height)k?p=v=Math.min(Math.max(q,p),l.top+l.height):b=!0;b||y.push("M",x,p,"L",u,v)}));return 0<y.length?t.crispPolyLine(y,f||1):null});z.prototype.getPlotBandPath=function(a,b){b=this.getPlotLinePath(b,null,null,!0);a=this.getPlotLinePath(a,null,null,!0);var c=[],d;if(a&&b)if(a.toString()===
b.toString())c=a,c.flat=!0;else for(d=0;d<a.length;d+=6)c.push("M",a[d+1],a[d+2],"L",a[d+4],a[d+5],b[d+4],b[d+5],b[d+1],b[d+2],"z");else c=null;return c};D.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};m===q&&(q.prototype.crispPolyLine=D.prototype.crispPolyLine);r(z.prototype,"hideCrosshair",function(a,b){a.call(this,b);this.crossLabel&&(this.crossLabel=
this.crossLabel.hide())});r(z.prototype,"drawCrosshair",function(a,b,c){var d,e;a.call(this,b,c);if(E(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){a=this.chart;var f=this.options.crosshair.label,g=this.horiz;d=this.opposite;e=this.left;var k=this.top,l=this.crossLabel,n,m=f.format,p="",r="inside"===this.options.tickPosition,q=!1!==this.crosshair.snap,t=0;b||(b=this.cross&&this.cross.e);n=g?"center":d?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";
l||(l=this.crossLabel=a.renderer.label(null,null,null,f.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:f.align||n,padding:h(f.padding,8),r:h(f.borderRadius,3),zIndex:2}).add(this.labelGroup),l.attr({fill:f.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:f.borderColor||"","stroke-width":f.borderWidth||0}).css(I({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},f.style)));
g?(n=q?c.plotX+e:b.chartX,k+=d?0:this.height):(n=d?this.width+e:0,k=q?c.plotY+k:b.chartY);m||f.formatter||(this.isDatetimeAxis&&(p="%b %d, %Y"),m="{value"+(p?":"+p:"")+"}");b=q?c[this.isXAxis?"x":"y"]:this.toValue(g?b.chartX:b.chartY);l.attr({text:m?u(m,{value:b}):f.formatter.call(this,b),x:n,y:k,visibility:"visible"});b=l.getBBox();if(g){if(r&&!d||!r&&d)k=l.y-b.height}else k=l.y-b.height/2;g?(d=e-b.x,e=e+this.width-b.x):(d="left"===this.labelAlign?e:0,e="right"===this.labelAlign?e+this.width:a.chartWidth);
l.translateX<d&&(t=d-l.translateX);l.translateX+b.width>=e&&(t=-(l.translateX+b.width-e));l.attr({x:n+t,y:k,anchorX:g?n:this.opposite?0:a.chartWidth,anchorY:g?this.opposite?a.chartHeight:0:k+b.height/2})}});c.init=function(){v.apply(this,arguments);this.setCompare(this.options.compare)};c.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;if(void 0!==b&&void 0!==d)return b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=
b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};c.processData=function(){var a,b=-1,c,d,e,f;y.apply(this,arguments);if(this.xAxis&&this.processedYData)for(c=this.processedXData,d=this.processedYData,e=d.length,this.pointArrayMap&&(b=H("close",this.pointArrayMap),-1===b&&(b=H(this.pointValKey||"y",this.pointArrayMap))),a=0;a<e-1;a++)if(f=d[a]&&-1<b?d[a][b]:d[a],J(f)&&c[a+1]>=this.xAxis.min&&0!==f){this.compareValue=f;break}};r(c,"getExtremes",function(a){var b;a.apply(this,
[].slice.call(arguments,1));this.modifyValue&&(b=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)],this.dataMin=t(b),this.dataMax=F(b))});z.prototype.setCompare=function(a,b){this.isXAxis||(w(this.series,function(b){b.setCompare(a)}),h(b,!0)&&this.chart.redraw())};k.prototype.tooltipFormatter=function(b){b=b.replace("{point.change}",(0<this.change?"+":"")+a.numberFormat(this.change,h(this.series.tooltipOptions.changeDecimals,2)));return G.apply(this,[b])};r(f.prototype,"render",function(a){this.chart.is3d&&
this.chart.is3d()||this.chart.polar||!this.xAxis||this.xAxis.isRadial||(!this.clipBox&&this.animate?(this.clipBox=b(this.chart.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=this.yAxis.len):this.chart[this.sharedClipKey]?this.chart[this.sharedClipKey].attr({width:this.xAxis.len,height:this.yAxis.len}):this.clipBox&&(this.clipBox.width=this.xAxis.len,this.clipBox.height=this.yAxis.len));a.call(this)});r(B.prototype,"getSelectedPoints",function(a){var b=a.call(this);w(this.series,function(a){a.hasGroupedData&&
(b=b.concat(p(a.points||[],function(a){return a.selected})))});return b});r(B.prototype,"update",function(a,c){"scrollbar"in c&&this.navigator&&(b(!0,this.options.scrollbar,c.scrollbar),this.navigator.update({},!1),delete c.scrollbar);return a.apply(this,Array.prototype.slice.call(arguments,1))})})(K)});