/*
 Highcharts JS v5.0.14-modified (2017-09-22)
 Highstock as a plugin for Highcharts

 (c) 2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(K){"object"===typeof module&&module.exports?module.exports=K:K(Highcharts)})(function(K){(function(a){var E=a.addEvent,m=a.Axis,t=a.Chart,w=a.css,C=a.dateFormat,H=a.defined,J=a.each,r=a.extend,p=a.noop,A=a.timeUnits,G=a.wrap;G(a.Series.prototype,"init",function(a){var b;a.apply(this,Array.prototype.slice.call(arguments,1));(b=this.xAxis)&&b.options.ordinal&&E(this,"updatedData",function(){delete b.ordinalIndex})});G(m.prototype,"getTimeTicks",function(a,b,d,e,F,n,g,f){var k=0,x,u,c={},h,
l,z,q=[],v=-Number.MAX_VALUE,D=this.options.tickPixelInterval;if(!this.options.ordinal&&!this.options.breaks||!n||3>n.length||void 0===d)return a.call(this,b,d,e,F);l=n.length;for(x=0;x<l;x++){z=x&&n[x-1]>e;n[x]<d&&(k=x);if(x===l-1||n[x+1]-n[x]>5*g||z){if(n[x]>v){for(u=a.call(this,b,n[k],n[x],F);u.length&&u[0]<=v;)u.shift();u.length&&(v=u[u.length-1]);q=q.concat(u)}k=x+1}if(z)break}a=u.info;if(f&&a.unitRange<=A.hour){x=q.length-1;for(k=1;k<x;k++)C("%d",q[k])!==C("%d",q[k-1])&&(c[q[k]]="day",h=!0);
h&&(c[q[0]]="day");a.higherRanks=c}q.info=a;if(f&&H(D)){f=a=q.length;x=[];var I;for(h=[];f--;)k=this.translate(q[f]),I&&(h[f]=I-k),x[f]=I=k;h.sort();h=h[Math.floor(h.length/2)];h<.6*D&&(h=null);f=q[a-1]>e?a-1:a;for(I=void 0;f--;)k=x[f],e=Math.abs(I-k),I&&e<.8*D&&(null===h||e<.8*h)?(c[q[f]]&&!c[q[f+1]]?(e=f+1,I=k):e=f,q.splice(e,1)):I=k}return q});r(m.prototype,{beforeSetTickPositions:function(){var a,b=[],d=!1,e,F=this.getExtremes(),n=F.min,g=F.max,f,B=this.isXAxis&&!!this.options.breaks,F=this.options.ordinal,
x=this.chart.options.chart.ignoreHiddenSeries;if(F||B){J(this.series,function(g,c){if(!(x&&!1===g.visible||!1===g.takeOrdinalPosition&&!B)&&(b=b.concat(g.processedXData),a=b.length,b.sort(function(h,c){return h-c}),a))for(c=a-1;c--;)b[c]===b[c+1]&&b.splice(c,1)});a=b.length;if(2<a){e=b[1]-b[0];for(f=a-1;f--&&!d;)b[f+1]-b[f]!==e&&(d=!0);!this.options.keepOrdinalPadding&&(b[0]-n>e||g-b[b.length-1]>e)&&(d=!0)}d?(this.ordinalPositions=b,e=this.ordinal2lin(Math.max(n,b[0]),!0),f=Math.max(this.ordinal2lin(Math.min(g,
b[b.length-1]),!0),1),this.ordinalSlope=g=(g-n)/(f-e),this.ordinalOffset=n-e*g):this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0}this.isOrdinal=F&&d;this.groupIntervalFactor=null},val2lin:function(a,b){var d=this.ordinalPositions;if(d){var e=d.length,k,n;for(k=e;k--;)if(d[k]===a){n=k;break}for(k=e-1;k--;)if(a>d[k]||0===k){a=(a-d[k])/(d[k+1]-d[k]);n=k+a;break}b=b?n:this.ordinalSlope*(n||0)+this.ordinalOffset}else b=a;return b},lin2val:function(a,b){var d=this.ordinalPositions;if(d){var e=
this.ordinalSlope,k=this.ordinalOffset,n=d.length-1,g;if(b)0>a?a=d[0]:a>n?a=d[n]:(n=Math.floor(a),g=a-n);else for(;n--;)if(b=e*n+k,a>=b){e=e*(n+1)+k;g=(a-b)/(e-b);break}return void 0!==g&&void 0!==d[n]?d[n]+(g?g*(d[n+1]-d[n]):0):a}return a},getExtendedPositions:function(){var a=this.chart,b=this.series[0].currentDataGrouping,d=this.ordinalIndex,e=b?b.count+b.unitName:"raw",F=this.getExtremes(),n,g;d||(d=this.ordinalIndex={});d[e]||(n={series:[],chart:a,getExtremes:function(){return{min:F.dataMin,
max:F.dataMax}},options:{ordinal:!0},val2lin:m.prototype.val2lin,ordinal2lin:m.prototype.ordinal2lin},J(this.series,function(f){g={xAxis:n,xData:f.xData,chart:a,destroyGroupedData:p};g.options={dataGrouping:b?{enabled:!0,forced:!0,approximation:"open",units:[[b.unitName,[b.count]]]}:{enabled:!1}};f.processData.apply(g);n.series.push(g)}),this.beforeSetTickPositions.apply(n),d[e]=n.ordinalPositions);return d[e]},getGroupIntervalFactor:function(a,b,d){var e;d=d.processedXData;var k=d.length,n=[];e=
this.groupIntervalFactor;if(!e){for(e=0;e<k-1;e++)n[e]=d[e+1]-d[e];n.sort(function(g,a){return g-a});n=n[Math.floor(k/2)];a=Math.max(a,d[0]);b=Math.min(b,d[k-1]);this.groupIntervalFactor=e=k*n/(b-a)}return e},postProcessTickInterval:function(a){var b=this.ordinalSlope;return b?this.options.breaks?this.closestPointRange:a/(b/this.closestPointRange):a}});m.prototype.ordinal2lin=m.prototype.val2lin;G(t.prototype,"pan",function(a,b){var d=this.xAxis[0],e=b.chartX,k=!1;if(d.options.ordinal&&d.series.length){var n=
this.mouseDownX,g=d.getExtremes(),f=g.dataMax,B=g.min,x=g.max,u=this.hoverPoints,c=d.closestPointRange,n=(n-e)/(d.translationSlope*(d.ordinalSlope||c)),h={ordinalPositions:d.getExtendedPositions()},c=d.lin2val,l=d.val2lin,z;h.ordinalPositions?1<Math.abs(n)&&(u&&J(u,function(q){q.setState()}),0>n?(u=h,z=d.ordinalPositions?d:h):(u=d.ordinalPositions?d:h,z=h),h=z.ordinalPositions,f>h[h.length-1]&&h.push(f),this.fixedRange=x-B,n=d.toFixedRange(null,null,c.apply(u,[l.apply(u,[B,!0])+n,!0]),c.apply(z,[l.apply(z,
[x,!0])+n,!0])),n.min>=Math.min(g.dataMin,B)&&n.max<=Math.max(f,x)&&d.setExtremes(n.min,n.max,!0,!1,{trigger:"pan"}),this.mouseDownX=e,w(this.container,{cursor:"move"})):k=!0}else k=!0;k&&a.apply(this,Array.prototype.slice.call(arguments,1))})})(K);(function(a){function E(){return Array.prototype.slice.call(arguments,1)}function m(a){a.apply(this);this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,t(this.pointArrayMap,["y"]))}var t=a.pick,w=a.wrap,C=a.each,H=a.extend,J=a.isArray,r=a.fireEvent,
p=a.Axis,A=a.Series;H(p.prototype,{isInBreak:function(a,k){var b=a.repeat||Infinity,d=a.from,e=a.to-a.from;k=k>=d?(k-d)%b:b-(d-k)%b;return a.inclusive?k<=e:k<e&&0!==k},isInAnyBreak:function(a,k){var b=this.options.breaks,d=b&&b.length,e,p,n;if(d){for(;d--;)this.isInBreak(b[d],a)&&(e=!0,p||(p=t(b[d].showPoints,this.isXAxis?!1:!0)));n=e&&k?e&&!p:e}return n}});w(p.prototype,"setTickPositions",function(a){a.apply(this,Array.prototype.slice.call(arguments,1));if(this.options.breaks){var k=this.tickPositions,
b=this.tickPositions.info,d=[],e;for(e=0;e<k.length;e++)this.isInAnyBreak(k[e])||d.push(k[e]);this.tickPositions=d;this.tickPositions.info=b}});w(p.prototype,"init",function(a,k,b){var d=this;b.breaks&&b.breaks.length&&(b.ordinal=!1);a.call(this,k,b);a=this.options.breaks;d.isBroken=J(a)&&!!a.length;d.isBroken&&(d.val2lin=function(a){var b=a,e,g;for(g=0;g<d.breakArray.length;g++)if(e=d.breakArray[g],e.to<=a)b-=e.len;else if(e.from>=a)break;else if(d.isInBreak(e,a)){b-=a-e.from;break}return b},d.lin2val=
function(a){var b,e;for(e=0;e<d.breakArray.length&&!(b=d.breakArray[e],b.from>=a);e++)b.to<a?a+=b.len:d.isInBreak(b,a)&&(a+=b.len);return a},d.setExtremes=function(a,b,d,g,f){for(;this.isInAnyBreak(a);)a-=this.closestPointRange;for(;this.isInAnyBreak(b);)b-=this.closestPointRange;p.prototype.setExtremes.call(this,a,b,d,g,f)},d.setAxisTranslation=function(a){p.prototype.setAxisTranslation.call(this,a);a=d.options.breaks;var b=[],k=[],g=0,f,e,x=d.userMin||d.min,u=d.userMax||d.max,c=t(d.pointRangePadding,
0),h,l;C(a,function(c){e=c.repeat||Infinity;d.isInBreak(c,x)&&(x+=c.to%e-x%e);d.isInBreak(c,u)&&(u-=u%e-c.from%e)});C(a,function(c){h=c.from;for(e=c.repeat||Infinity;h-e>x;)h-=e;for(;h<x;)h+=e;for(l=h;l<u;l+=e)b.push({value:l,move:"in"}),b.push({value:l+(c.to-c.from),move:"out",size:c.breakSize})});b.sort(function(c,q){return c.value===q.value?("in"===c.move?0:1)-("in"===q.move?0:1):c.value-q.value});f=0;h=x;C(b,function(c){f+="in"===c.move?1:-1;1===f&&"in"===c.move&&(h=c.value);0===f&&(k.push({from:h,
to:c.value,len:c.value-h-(c.size||0)}),g+=c.value-h-(c.size||0))});d.breakArray=k;d.unitLength=u-x-g+c;r(d,"afterBreaks");d.options.staticScale?d.transA=d.options.staticScale:d.unitLength&&(d.transA*=(u-d.min+c)/d.unitLength);c&&(d.minPixelPadding=d.transA*d.minPointOffset);d.min=x;d.max=u})});w(A.prototype,"generatePoints",function(a){a.apply(this,E(arguments));var k=this.xAxis,b=this.yAxis,d=this.points,e,p=d.length,n=this.options.connectNulls,g;if(k&&b&&(k.options.breaks||b.options.breaks))for(;p--;)e=
d[p],g=null===e.y&&!1===n,g||!k.isInAnyBreak(e.x,!0)&&!b.isInAnyBreak(e.y,!0)||(d.splice(p,1),this.data[p]&&this.data[p].destroyElements())});a.Series.prototype.drawBreaks=function(a,k){var b=this,d=b.points,e,p,n,g;a&&C(k,function(f){e=a.breakArray||[];p=a.isXAxis?a.min:t(b.options.threshold,a.min);C(d,function(b){g=t(b["stack"+f.toUpperCase()],b[f]);C(e,function(f){n=!1;if(p<f.from&&g>f.to||p>f.from&&g<f.from)n="pointBreak";else if(p<f.from&&g>f.from&&g<f.to||p>f.from&&g>f.to&&g<f.from)n="pointInBreak";
n&&r(a,n,{point:b,brk:f})})})})};a.Series.prototype.gappedPath=function(){var p=this.options.gapSize,k=this.points.slice(),b=k.length-1,d=this.yAxis,e;if(p&&0<b)for("value"!==this.options.gapUnit&&(p*=this.closestPointRange);b--;)k[b+1].x-k[b].x>p&&(e=(k[b].x+k[b+1].x)/2,k.splice(b+1,0,{isNull:!0,x:e}),this.options.stacking&&(e=d.stacks[this.stackKey][e]=new a.StackItem(d,d.options.stackLabels,!1,e,this.stack),e.total=0));return this.getGraphPath(k)};w(a.seriesTypes.column.prototype,"drawPoints",
m);w(a.Series.prototype,"drawPoints",m)})(K);(function(a){var E=a.arrayMax,m=a.arrayMin,t=a.Axis,w=a.defaultPlotOptions,C=a.defined,H=a.each,J=a.extend,r=a.format,p=a.isNumber,A=a.merge,G=a.pick,k=a.Point,b=a.Tooltip,d=a.wrap,e=a.Series.prototype,F=e.processData,n=e.generatePoints,g=e.destroy,f={approximation:"average",groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],
minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},B={line:{},spline:{},area:{},areaspline:{},column:{approximation:"sum",groupPixelWidth:10},arearange:{approximation:"range"},areasplinerange:{approximation:"range"},columnrange:{approximation:"range",groupPixelWidth:10},candlestick:{approximation:"ohlc",
groupPixelWidth:10},ohlc:{approximation:"ohlc",groupPixelWidth:5}},x=a.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]],u={sum:function(c){var a=c.length,l;if(!a&&c.hasNulls)l=null;else if(a)for(l=0;a--;)l+=c[a];return l},average:function(c){var a=c.length;c=u.sum(c);p(c)&&a&&(c/=a);return c},averages:function(){var c=[];H(arguments,function(a){c.push(u.average(a))});
return c},open:function(c){return c.length?c[0]:c.hasNulls?null:void 0},high:function(c){return c.length?E(c):c.hasNulls?null:void 0},low:function(c){return c.length?m(c):c.hasNulls?null:void 0},close:function(c){return c.length?c[c.length-1]:c.hasNulls?null:void 0},ohlc:function(c,a,l,g){c=u.open(c);a=u.high(a);l=u.low(l);g=u.close(g);if(p(c)||p(a)||p(l)||p(g))return[c,a,l,g]},range:function(c,a){c=u.low(c);a=u.high(a);if(p(c)||p(a))return[c,a];if(null===c&&null===a)return null}};e.groupData=function(c,
a,l,g){var q=this.data,v=this.options.data,h=[],b=[],d=[],z=c.length,y,e,k=!!a,n=[];g="function"===typeof g?g:u[g]||B[this.type]&&u[B[this.type].approximation]||u[f.approximation];var x=this.pointArrayMap,M=x&&x.length,A=0;e=0;var r,m;M?H(x,function(){n.push([])}):n.push([]);r=M||1;for(m=0;m<=z&&!(c[m]>=l[0]);m++);for(m;m<=z;m++){for(;void 0!==l[A+1]&&c[m]>=l[A+1]||m===z;){y=l[A];this.dataGroupInfo={start:e,length:n[0].length};e=g.apply(this,n);void 0!==e&&(h.push(y),b.push(e),d.push(this.dataGroupInfo));
e=m;for(y=0;y<r;y++)n[y].length=0,n[y].hasNulls=!1;A+=1;if(m===z)break}if(m===z)break;if(x){y=this.cropStart+m;var G=q&&q[y]||this.pointClass.prototype.applyOptions.apply({series:this},[v[y]]),C;for(y=0;y<M;y++)C=G[x[y]],p(C)?n[y].push(C):null===C&&(n[y].hasNulls=!0)}else y=k?a[m]:null,p(y)?n[0].push(y):null===y&&(n[0].hasNulls=!0)}return[h,b,d]};e.processData=function(){var c=this.chart,a=this.options.dataGrouping,l=!1!==this.allowDG&&a&&G(a.enabled,c.options.isStock),g=this.visible||!c.options.chart.ignoreHiddenSeries,
q;this.forceCrop=l;this.groupPixelWidth=null;this.hasProcessed=!0;if(!1!==F.apply(this,arguments)&&l){this.destroyGroupedData();var v=this.processedXData,D=this.processedYData,f=c.plotSizeX,c=this.xAxis,b=c.options.ordinal,d=this.groupPixelWidth=c.getGroupPixelWidth&&c.getGroupPixelWidth();if(d){this.isDirty=q=!0;this.points=null;var y=c.getExtremes(),l=y.min,y=y.max,b=b&&c.getGroupIntervalFactor(l,y,this)||1,f=d*(y-l)/f*b,d=c.getTimeTicks(c.normalizeTimeTickInterval(f,a.units||x),Math.min(l,v[0]),
Math.max(y,v[v.length-1]),c.options.startOfWeek,v,this.closestPointRange),v=e.groupData.apply(this,[v,D,d,a.approximation]),D=v[0],b=v[1];if(a.smoothed&&D.length){a=D.length-1;for(D[a]=Math.min(D[a],y);a--&&0<a;)D[a]+=f/2;D[0]=Math.max(D[0],l)}this.currentDataGrouping=d.info;this.closestPointRange=d.info.totalRange;this.groupMap=v[2];C(D[0])&&D[0]<c.dataMin&&g&&(c.min===c.dataMin&&(c.min=D[0]),c.dataMin=D[0]);this.processedXData=D;this.processedYData=b}else this.currentDataGrouping=this.groupMap=
null;this.hasGroupedData=q}};e.destroyGroupedData=function(){var a=this.groupedData;H(a||[],function(c,l){c&&(a[l]=c.destroy?c.destroy():null)});this.groupedData=null};e.generatePoints=function(){n.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};d(k.prototype,"update",function(c){this.dataGroup?a.error(24):c.apply(this,[].slice.call(arguments,1))});d(b.prototype,"tooltipFooterHeaderFormatter",function(c,g,l){var h=g.series,q=h.tooltipOptions,v=h.options.dataGrouping,
f=q.xDateFormat,b,d=h.xAxis,e=a.dateFormat;return d&&"datetime"===d.options.type&&v&&p(g.key)?(c=h.currentDataGrouping,v=v.dateTimeLabelFormats,c?(d=v[c.unitName],1===c.count?f=d[0]:(f=d[1],b=d[2])):!f&&v&&(f=this.getXDateFormat(g,q,d)),f=e(f,g.key),b&&(f+=e(b,g.key+c.totalRange-1)),r(q[(l?"footer":"header")+"Format"],{point:J(g.point,{key:f}),series:h})):c.call(this,g,l)});e.destroy=function(){for(var a=this.groupedData||[],h=a.length;h--;)a[h]&&a[h].destroy();g.apply(this)};d(e,"setOptions",function(a,
g){a=a.call(this,g);var c=this.type,h=this.chart.options.plotOptions,q=w[c].dataGrouping;B[c]&&(q||(q=A(f,B[c])),a.dataGrouping=A(q,h.series&&h.series.dataGrouping,h[c].dataGrouping,g.dataGrouping));this.chart.options.isStock&&(this.requireSorting=!0);return a});d(t.prototype,"setScale",function(a){a.call(this);H(this.series,function(a){a.hasProcessed=!1})});t.prototype.getGroupPixelWidth=function(){var a=this.series,g=a.length,l,f=0,q=!1,v;for(l=g;l--;)(v=a[l].options.dataGrouping)&&(f=Math.max(f,
v.groupPixelWidth));for(l=g;l--;)(v=a[l].options.dataGrouping)&&a[l].hasProcessed&&(g=(a[l].processedXData||a[l].data).length,a[l].groupPixelWidth||g>this.chart.plotSizeX/f||g&&v.forced)&&(q=!0);return q?f:0};t.prototype.setDataGrouping=function(a,g){var c;g=G(g,!0);a||(a={forced:!1,units:null});if(this instanceof t)for(c=this.series.length;c--;)this.series[c].update({dataGrouping:a},!1);else H(this.chart.options.series,function(c){c.dataGrouping=a},!1);g&&this.chart.redraw()}})(K);(function(a){var E=
a.each,m=a.Point,t=a.seriesType,w=a.seriesTypes;t("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'\x3cspan class\x3d"highcharts-color-{point.colorIndex}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eOpen: {point.open}\x3cbr/\x3eHigh: {point.high}\x3cbr/\x3eLow: {point.low}\x3cbr/\x3eClose: {point.close}\x3cbr/\x3e'},threshold:null,stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(a){return[a.open,a.high,a.low,a.close]},pointValKey:"close",
translate:function(){var a=this,m=a.yAxis,t=!!a.modifyValue,r=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];w.column.prototype.translate.apply(a);E(a.points,function(p){E([p.open,p.high,p.low,p.close,p.low],function(A,G){null!==A&&(t&&(A=a.modifyValue(A)),p[r[G]]=m.toPixels(A,!0))});p.tooltipPos[1]=p.plotHigh+m.pos-a.chart.plotTop})},drawPoints:function(){var a=this,m=a.chart;E(a.points,function(t){var r,p,A,G,k=t.graphic,b,d=!k;void 0!==t.plotY&&(k||(t.graphic=k=m.renderer.path().add(a.group)),
p=k.strokeWidth()%2/2,b=Math.round(t.plotX)-p,A=Math.round(t.shapeArgs.width/2),G=["M",b,Math.round(t.yBottom),"L",b,Math.round(t.plotHigh)],null!==t.open&&(r=Math.round(t.plotOpen)+p,G.push("M",b,r,"L",b-A,r)),null!==t.close&&(r=Math.round(t.plotClose)+p,G.push("M",b,r,"L",b+A,r)),k[d?"attr":"animate"]({d:G}).addClass(t.getClassName(),!0))})},animate:null},{getClassName:function(){return m.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})})(K);
(function(a){var E=a.defaultPlotOptions,m=a.each,t=a.merge;a=a.seriesType;a("candlestick","ohlc",t(E.column,{states:{hover:{lineWidth:2}},tooltip:E.ohlc.tooltip,threshold:null}),{drawPoints:function(){var a=this,t=a.chart;m(a.points,function(m){var w=m.graphic,r,p,A,G,k,b,d,e=!w;void 0!==m.plotY&&(w||(m.graphic=w=t.renderer.path().add(a.group)),k=w.strokeWidth()%2/2,b=Math.round(m.plotX)-k,r=m.plotOpen,p=m.plotClose,A=Math.min(r,p),r=Math.max(r,p),d=Math.round(m.shapeArgs.width/2),p=Math.round(A)!==
Math.round(m.plotHigh),G=r!==m.yBottom,A=Math.round(A)+k,r=Math.round(r)+k,k=[],k.push("M",b-d,r,"L",b-d,A,"L",b+d,A,"L",b+d,r,"Z","M",b,A,"L",b,p?Math.round(m.plotHigh):A,"M",b,r,"L",b,G?Math.round(m.yBottom):r),w[e?"attr":"animate"]({d:k}).addClass(m.getClassName(),!0))})}})})(K);(function(a){var E=a.addEvent,m=a.each,t=a.noop,w=a.seriesType,C=a.seriesTypes,H=a.TrackerMixin,J=a.SVGRenderer.prototype.symbols,r=a.stableSort;w("flags","column",{pointRange:0,shape:"flag",stackDistance:12,textAlign:"center",
tooltip:{pointFormat:"{point.text}\x3cbr/\x3e"},threshold:null,y:-30},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:a.Series.prototype.init,translate:function(){C.column.prototype.translate.apply(this);var a=this.options,A=this.chart,t=this.points,k=t.length-1,b,d,e=a.onSeries;b=e&&A.get(e);var a=a.onKey||"y",e=b&&b.options.step,w=b&&b.points,n=w&&w.length,g=this.xAxis,f=this.yAxis,B=g.getExtremes(),x=0,u,c,h;if(b&&b.visible&&n)for(x=
(b.pointXOffset||0)+(b.barW||0)/2,b=b.currentDataGrouping,c=w[n-1].x+(b?b.totalRange:0),r(t,function(a,c){return a.x-c.x}),a="plot"+a[0].toUpperCase()+a.substr(1);n--&&t[k]&&!(b=t[k],u=w[n],u.x<=b.x&&void 0!==u[a]&&(b.x<=c&&(b.plotY=u[a],u.x<b.x&&!e&&(h=w[n+1])&&void 0!==h[a]&&(b.plotY+=(b.x-u.x)/(h.x-u.x)*(h[a]-u[a]))),k--,n++,0>k)););m(t,function(a,c){var q;void 0===a.plotY&&(a.x>=B.min&&a.x<=B.max?a.plotY=A.chartHeight-g.bottom-(g.opposite?g.height:0)+g.offset-f.top:a.shapeArgs={});a.plotX+=x;
(d=t[c-1])&&d.plotX===a.plotX&&(void 0===d.stackIndex&&(d.stackIndex=0),q=d.stackIndex+1);a.stackIndex=q})},drawPoints:function(){var p=this.points,m=this.chart,t=m.renderer,k,b,d=this.options,e=d.y,r,n,g,f,B,x,u,c=this.yAxis;for(n=p.length;n--;)g=p[n],u=g.plotX>this.xAxis.len,k=g.plotX,f=g.stackIndex,r=g.options.shape||d.shape,b=g.plotY,void 0!==b&&(b=g.plotY+e-(void 0!==f&&f*d.stackDistance)),B=f?void 0:g.plotX,x=f?void 0:g.plotY,f=g.graphic,void 0!==b&&0<=k&&!u?(f||(f=g.graphic=t.label("",null,
null,r,null,null,d.useHTML).attr({align:"flag"===r?"left":"center",width:d.width,height:d.height,"text-align":d.textAlign}).addClass("highcharts-point").add(this.markerGroup),g.graphic.div&&(g.graphic.div.point=g)),0<k&&(k-=f.strokeWidth()%2),f.attr({text:g.options.title||d.title||"A",x:k,y:b,anchorX:B,anchorY:x}),g.tooltipPos=m.inverted?[c.len+c.pos-m.plotLeft-b,this.xAxis.len-k]:[k,b+c.pos-m.plotTop]):f&&(g.graphic=f.destroy());d.useHTML&&a.wrap(this.markerGroup,"on",function(c){return a.SVGElement.prototype.on.apply(c.apply(this,
[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;H.drawTrackerPoint.apply(this);m(a,function(p){var t=p.graphic;t&&E(t.element,"mouseover",function(){0<p.stackIndex&&!p.raised&&(p._y=t.y,t.attr({y:p._y-8}),p.raised=!0);m(a,function(a){a!==p&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:t,buildKDTree:t,setClip:t});J.flag=function(a,m,t,k,b){return["M",b&&b.anchorX||a,b&&b.anchorY||m,"L",a,m+k,a,m,a+t,m,a+t,m+k,a,m+k,"Z"]};
m(["circle","square"],function(a){J[a+"pin"]=function(m,p,k,b,d){var e=d&&d.anchorX;d=d&&d.anchorY;"circle"===a&&b>k&&(m-=Math.round((b-k)/2),k=b);m=J[a](m,p,k,b);e&&d&&m.push("M",e,p>d?p:p+b,"L",e,d);return m}})})(K);(function(a){function E(a,f,b){this.init(a,f,b)}var m=a.addEvent,t=a.Axis,w=a.correctFloat,C=a.defaultOptions,H=a.defined,J=a.destroyObjectProperties,r=a.each,p=a.fireEvent,A=a.hasTouch,G=a.isTouchDevice,k=a.merge,b=a.pick,d=a.removeEvent,e=a.wrap,F,n={height:G?20:14,barBorderRadius:0,
buttonBorderRadius:0,liveRedraw:a.svg&&!G,margin:10,minWidth:6,step:.2,zIndex:3};C.scrollbar=k(!0,n,C.scrollbar);a.swapXY=F=function(a,f){var g=a.length,b;if(f)for(f=0;f<g;f+=3)b=a[f+1],a[f+1]=a[f+2],a[f+2]=b;return a};E.prototype={init:function(a,f,d){this.scrollbarButtons=[];this.renderer=a;this.userOptions=f;this.options=k(n,f);this.chart=d;this.size=b(this.options.size,this.options.height);f.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,f=this.options,
b=this.size,d;this.group=d=a.g("scrollbar").attr({zIndex:f.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:f.trackBorderRadius||0,height:b,width:b}).add(d);this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(d);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:b,width:b,r:f.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(F(["M",
-3,b/4,"L",-3,2*b/3,"M",0,b/4,"L",0,2*b/3,"M",3,b/4,"L",3,2*b/3],f.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,f,b,d){var g=this.options.vertical,c=0,h=this.rendered?"animate":"attr";this.x=a;this.y=f+this.trackBorderWidth;this.width=b;this.xOffset=
this.height=d;this.yOffset=c;g?(this.width=this.yOffset=b=c=this.size,this.xOffset=f=0,this.barWidth=d-2*b,this.x=a+=this.options.margin):(this.height=this.xOffset=d=f=this.size,this.barWidth=b-2*d,this.y+=this.options.margin);this.group[h]({translateX:a,translateY:this.y});this.track[h]({width:b,height:d});this.scrollbarButtons[1][h]({translateX:g?0:b-f,translateY:g?d-c:0})},drawScrollbarButton:function(a){var g=this.renderer,b=this.scrollbarButtons,d=this.options,e=this.size,c;c=g.g().add(this.group);
b.push(c);c=g.rect().addClass("highcharts-scrollbar-button").add(c);c.attr(c.crisp({x:-.5,y:-.5,width:e+1,height:e+1,r:d.buttonBorderRadius},c.strokeWidth()));g.path(F(["M",e/2+(a?-1:1),e/2-3,"L",e/2+(a?-1:1),e/2+3,"L",e/2+(a?2:-2),e/2],d.vertical)).addClass("highcharts-scrollbar-arrow").add(b[a])},setRange:function(a,b){var g=this.options,f=g.vertical,d=g.minWidth,c=this.barWidth,h,l,e=this.rendered&&!this.hasDragged?"animate":"attr";H(c)&&(a=Math.max(a,0),h=Math.ceil(c*a),this.calculatedWidth=l=
w(c*Math.min(b,1)-h),l<d&&(h=(c-d+l)*a,l=d),d=Math.floor(h+this.xOffset+this.yOffset),c=l/2-.5,this.from=a,this.to=b,f?(this.scrollbarGroup[e]({translateY:d}),this.scrollbar[e]({height:l}),this.scrollbarRifles[e]({translateY:c}),this.scrollbarTop=d,this.scrollbarLeft=0):(this.scrollbarGroup[e]({translateX:d}),this.scrollbar[e]({width:l}),this.scrollbarRifles[e]({translateX:c}),this.scrollbarLeft=d,this.scrollbarTop=0),12>=l?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0),!1===g.showFull&&
(0>=a&&1<=b?this.group.hide():this.group.show()),this.rendered=!0)},initEvents:function(){var a=this;a.mouseMoveHandler=function(b){var d=a.chart.pointer.normalize(b),f=a.options.vertical?"chartY":"chartX",g=a.initPositions;!a.grabbedCenter||b.touches&&0===b.touches[0][f]||(d=a.cursorToScrollbarPosition(d)[f],f=a[f],f=d-f,a.hasDragged=!0,a.updatePosition(g[0]+f,g[1]+f),a.hasDragged&&p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};a.mouseUpHandler=function(b){a.hasDragged&&
p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(b){b=a.chart.pointer.normalize(b);b=a.cursorToScrollbarPosition(b);a.chartX=b.chartX;a.chartY=b.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(b){var d=w(a.to-a.from)*a.options.step;a.updatePosition(w(a.from-d),w(a.to-d));p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.buttonToMaxClick=
function(b){var d=(a.to-a.from)*a.options.step;a.updatePosition(a.from+d,a.to+d);p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.trackClick=function(b){var d=a.chart.pointer.normalize(b),f=a.to-a.from,g=a.y+a.scrollbarTop,c=a.x+a.scrollbarLeft;a.options.vertical&&d.chartY>g||!a.options.vertical&&d.chartX>c?a.updatePosition(a.from+f,a.to+f):a.updatePosition(a.from-f,a.to-f);p(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})}},cursorToScrollbarPosition:function(a){var b=
this.options,b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}},updatePosition:function(a,b){1<b&&(a=w(1-w(b-a)),b=1);0>a&&(b=w(b-a),a=0);this.from=a;this.to=b},update:function(a){this.destroy();this.init(this.chart.renderer,k(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,d=this.scrollbarGroup.element,e=this.mouseDownHandler,
k=this.mouseMoveHandler,c=this.mouseUpHandler,a=[[b[a[0]].element,"click",this.buttonToMinClick],[b[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[d,"mousedown",e],[d.ownerDocument,"mousemove",k],[d.ownerDocument,"mouseup",c]];A&&a.push([d,"touchstart",e],[d.ownerDocument,"touchmove",k],[d.ownerDocument,"touchend",c]);r(a,function(a){m.apply(null,a)});this._events=a},removeEvents:function(){r(this._events,function(a){d.apply(null,a)});this._events.length=
0},destroy:function(){var a=this.chart.scroller;this.removeEvents();r(["track","scrollbarRifles","scrollbar","scrollbarGroup","group"],function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,J(a.scrollbarButtons))}};e(t.prototype,"init",function(a){var d=this;a.apply(d,Array.prototype.slice.call(arguments,1));d.options.scrollbar&&d.options.scrollbar.enabled&&(d.options.scrollbar.vertical=!d.horiz,d.options.startOnTick=d.options.endOnTick=!1,
d.scrollbar=new E(d.chart.renderer,d.options.scrollbar,d.chart),m(d.scrollbar,"changed",function(a){var e=Math.min(b(d.options.min,d.min),d.min,d.dataMin),f=Math.max(b(d.options.max,d.max),d.max,d.dataMax)-e,c;d.horiz&&!d.reversed||!d.horiz&&d.reversed?(c=e+f*this.to,e+=f*this.from):(c=e+f*(1-this.from),e+=f*(1-this.to));d.setExtremes(e,c,!0,!1,a)}))});e(t.prototype,"render",function(a){var d=Math.min(b(this.options.min,this.min),this.min,b(this.dataMin,this.min)),e=Math.max(b(this.options.max,this.max),
this.max,b(this.dataMax,this.max)),g=this.scrollbar,k=this.titleOffset||0;a.apply(this,Array.prototype.slice.call(arguments,1));if(g){this.horiz?(g.position(this.left,this.top+this.height+2+this.chart.scrollbarsOffsets[1]+(this.opposite?0:k+this.axisTitleMargin+this.offset),this.width,this.height),k=1):(g.position(this.left+this.width+2+this.chart.scrollbarsOffsets[0]+(this.opposite?k+this.axisTitleMargin+this.offset:0),this.top,this.width,this.height),k=0);if(!this.opposite&&!this.horiz||this.opposite&&
this.horiz)this.chart.scrollbarsOffsets[k]+=this.scrollbar.size+this.scrollbar.options.margin;isNaN(d)||isNaN(e)||!H(this.min)||!H(this.max)?g.setRange(0,0):(k=(this.min-d)/(e-d),d=(this.max-d)/(e-d),this.horiz&&!this.reversed||!this.horiz&&this.reversed?g.setRange(k,d):g.setRange(1-d,1-k))}});e(t.prototype,"getOffset",function(a){var b=this.horiz?2:1,d=this.scrollbar;a.apply(this,Array.prototype.slice.call(arguments,1));d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=d.size+d.options.margin)});
e(t.prototype,"destroy",function(a){this.scrollbar&&(this.scrollbar=this.scrollbar.destroy());a.apply(this,Array.prototype.slice.call(arguments,1))});a.Scrollbar=E})(K);(function(a){function E(a){this.init(a)}var m=a.addEvent,t=a.Axis,w=a.Chart,C=a.defaultOptions,H=a.defined,J=a.destroyObjectProperties,r=a.each,p=a.erase,A=a.error,G=a.extend,k=a.grep,b=a.hasTouch,d=a.isArray,e=a.isNumber,F=a.isObject,n=a.merge,g=a.pick,f=a.removeEvent,B=a.Scrollbar,x=a.Series,u=a.seriesTypes,c=a.wrap,h=a.swapXY,l=
[].concat(a.defaultDataGroupingUnits),z=function(a){var q=k(arguments,e);if(q.length)return Math[a].apply(0,q)};l[4]=["day",[1,2,3,4]];l[5]=["week",[1,2,3]];G(C,{navigator:{height:40,margin:25,maskInside:!0,series:{type:void 0===u.areaspline?"line":"areaspline",compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:l},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},
pointRange:0,threshold:null},xAxis:{className:"highcharts-navigator-xaxis",tickLength:0,tickPixelInterval:200,labels:{align:"left",x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});E.prototype={drawHandle:function(a,c,b,d){this.handles[c][d](b?{translateX:Math.round(this.left+this.height/2-8),translateY:Math.round(this.top+parseInt(a,10)+.5)}:
{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-8)})},getHandlePath:function(a){return h(["M",-4.5,.5,"L",3.5,.5,"L",3.5,15.5,"L",-4.5,15.5,"L",-4.5,.5,"M",-1.5,4,"L",-1.5,12,"M",.5,4,"L",.5,12],a)},drawOutline:function(a,c,b,d){var q=this.navigatorOptions.maskInside,v=this.outline.strokeWidth(),l=v/2,v=v%2/2,h=this.outlineHeight,D=this.scrollbarHeight,e=this.size,f=this.left-D,g=this.top;b?(f-=l,b=g+c+v,c=g+a+v,a=["M",f+h,g-D-v,"L",f+h,b,"L",f,b,"L",
f,c,"L",f+h,c,"L",f+h,g+e+D].concat(q?["M",f+h,b-l,"L",f+h,c+l]:[])):(a+=f+D-v,c+=f+D-v,g+=l,a=["M",f,g,"L",a,g,"L",a,g+h,"L",c,g+h,"L",c,g,"L",f+e+2*D,g].concat(q?["M",a-l,g,"L",c+l,g]:[]));this.outline[d]({d:a})},drawMasks:function(a,c,b,d){var q=this.left,l=this.top,v=this.height,h,D,e,f;b?(e=[q,q,q],f=[l,l+a,l+c],D=[v,v,v],h=[a,c-a,this.size-c]):(e=[q,q+a,q+c],f=[l,l,l],D=[a,c-a,this.size-c],h=[v,v,v]);r(this.shades,function(a,q){a[d]({x:e[q],y:f[q],width:D[q],height:h[q]})})},renderElements:function(){var a=
this,c=a.navigatorOptions.maskInside,b=a.chart,d=b.inverted,l=b.renderer,h;a.navigatorGroup=h=l.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();r([!c,c,!c],function(q,c){a.shades[c]=l.rect().addClass("highcharts-navigator-mask"+(1===c?"-inside":"-outside")).add(h)});a.outline=l.path().addClass("highcharts-navigator-outline").add(h);r([0,1],function(q){a.handles[q]=l.path(a.getHandlePath(d)).attr({zIndex:7-q}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][q]).add(h)})},
update:function(a){r(this.series||[],function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();n(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(a,c,b,d){var q=this.chart,l,h,v=this.scrollbarHeight,D,f=this.xAxis;l=f.fake?q.xAxis[0]:f;var k=this.navigatorEnabled,z,I=this.rendered;h=q.inverted;var n=q.xAxis[0].minRange;if(!this.hasDragged||H(b)){if(!e(a)||!e(c))if(I)b=0,d=f.width;else return;this.left=g(f.left,q.plotLeft+v+(h?q.plotWidth:
0));this.size=z=D=g(f.len,(h?q.plotHeight:q.plotWidth)-2*v);q=h?v:D+2*v;b=g(b,f.toPixels(a,!0));d=g(d,f.toPixels(c,!0));e(b)&&Infinity!==Math.abs(b)||(b=0,d=q);a=f.toValue(b,!0);c=f.toValue(d,!0);if(Math.abs(c-a)<n)if(this.grabbedLeft)b=f.toPixels(c-n,!0);else if(this.grabbedRight)d=f.toPixels(a+n,!0);else return;this.zoomedMax=Math.min(Math.max(b,d,0),z);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(b,d),0),z);this.range=this.zoomedMax-this.zoomedMin;z=
Math.round(this.zoomedMax);b=Math.round(this.zoomedMin);k&&(this.navigatorGroup.attr({visibility:"visible"}),I=I&&!this.hasDragged?"animate":"attr",this.drawMasks(b,z,h,I),this.drawOutline(b,z,h,I),this.drawHandle(b,0,h,I),this.drawHandle(z,1,h,I));this.scrollbar&&(h?(h=this.top-v,l=this.left-v+(k||!l.opposite?0:(l.titleOffset||0)+l.axisTitleMargin),v=D+2*v):(h=this.top+(k?this.height:-v),l=this.left-v),this.scrollbar.position(l,h,q,v),this.scrollbar.setRange(this.zoomedMin/D,this.zoomedMax/D));this.rendered=
!0}},addMouseEvents:function(){var a=this,c=a.chart,d=c.container,l=[],h,f;a.mouseMoveHandler=h=function(c){a.onMouseMove(c)};a.mouseUpHandler=f=function(c){a.onMouseUp(c)};l=a.getPartsEvents("mousedown");l.push(m(d,"mousemove",h),m(d.ownerDocument,"mouseup",f));b&&(l.push(m(d,"touchmove",h),m(d.ownerDocument,"touchend",f)),l.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=l;a.series&&a.series[0]&&l.push(m(a.series[0].xAxis,"foundExtremes",function(){c.navigator.modifyNavigatorAxisExtremes()}))},
getPartsEvents:function(a){var c=this,q=[];r(["shades","handles"],function(b){r(c[b],function(d,l){q.push(m(d.element,a,function(a){c[b+"Mousedown"](a,l)}))})});return q},shadesMousedown:function(a,c){a=this.chart.pointer.normalize(a);var b=this.chart,d=this.xAxis,q=this.zoomedMin,l=this.left,h=this.size,v=this.range,f=a.chartX,e;b.inverted&&(f=a.chartY,l=this.top);1===c?(this.grabbedCenter=f,this.fixedWidth=v,this.dragOffset=f-q):(a=f-l-v/2,0===c?a=Math.max(0,a):2===c&&a+v>=h&&(a=h-v,e=this.getUnionExtremes().dataMax),
a!==q&&(this.fixedWidth=v,c=d.toFixedRange(a,a+v,null,e),b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,null,{trigger:"navigator"})))},handlesMousedown:function(a,c){this.chart.pointer.normalize(a);a=this.chart;var b=a.xAxis[0],d=a.inverted&&!b.reversed||!a.inverted&&b.reversed;0===c?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?b.min:b.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?b.max:b.min);a.fixedRange=null},
onMouseMove:function(a){var c=this,b=c.chart,d=c.left,q=c.navigatorSize,l=c.range,h=c.dragOffset,f=b.inverted;a.touches&&0===a.touches[0].pageX||(a=b.pointer.normalize(a),b=a.chartX,f&&(d=c.top,b=a.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,b-d,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,b-d)):c.grabbedCenter&&(c.hasDragged=!0,b<h?b=h:b>q+h-l&&(b=q+h-l),c.render(0,0,b-h,b-h+l)),c.hasDragged&&c.scrollbar&&c.scrollbar.options.liveRedraw&&(a.DOMType=a.type,
setTimeout(function(){c.onMouseUp(a)},0)))},onMouseUp:function(a){var c=this.chart,b=this.xAxis,d=this.scrollbar,q,l,h=a.DOMEvent||a;(!this.hasDragged||d&&d.hasDragged)&&"scrollbar"!==a.trigger||(this.zoomedMin===this.otherHandlePos?q=this.fixedExtreme:this.zoomedMax===this.otherHandlePos&&(l=this.fixedExtreme),this.zoomedMax===this.size&&(l=this.getUnionExtremes().dataMax),b=b.toFixedRange(this.zoomedMin,this.zoomedMax,q,l),H(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),
!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:h}));"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(r(this.eventsToUnbind,function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==
this.navigatorOptions.adaptToUpdatedData&&r(a,function(a){f(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&f(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var b=a.options,d=b.navigator,l=d.enabled,h=b.scrollbar,q=h.enabled,b=l?d.height:0,f=q?h.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=f;this.scrollbarEnabled=q;this.navigatorEnabled=l;this.navigatorOptions=d;this.scrollbarOptions=h;this.outlineHeight=
b+f;this.opposite=g(d.opposite,!l&&a.inverted);var e=this,h=e.baseSeries,q=a.xAxis.length,k=a.yAxis.length,p=h&&h[0]&&h[0].xAxis||a.xAxis[0];a.extraMargin={type:e.opposite?"plotTop":"marginBottom",value:(l||!a.inverted?e.outlineHeight:0)+d.margin};a.inverted&&(a.extraMargin.type=e.opposite?"marginRight":"plotLeft");a.isDirtyBox=!0;e.navigatorEnabled?(e.xAxis=new t(a,n({breaks:p.options.breaks,ordinal:p.options.ordinal},d.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",
index:q,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[f,0,-f,0],width:b}:{offsets:[0,-f,0,f],height:b})),e.yAxis=new t(a,n(d.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),h||d.series.data?e.updateNavigatorSeries():0===a.series.length&&c(a,"redraw",function(c,b){0<a.series.length&&!e.series&&(e.setBaseSeries(),a.redraw=c);c.call(a,b)}),e.renderElements(),e.addMouseEvents()):
e.xAxis={translate:function(c,b){var d=a.xAxis[0],l=d.getExtremes(),h=d.len-2*f,q=z("min",d.options.min,l.dataMin),d=z("max",d.options.max,l.dataMax)-q;return b?c*d/h+q:h*(c-q)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:t.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=e.scrollbar=new B(a.renderer,n(a.options.scrollbar,{margin:e.navigatorEnabled?0:10,vertical:a.inverted}),a),m(e.scrollbar,"changed",function(c){var b=
e.size,d=b*this.to,b=b*this.from;e.hasDragged=e.scrollbar.hasDragged;e.render(0,0,b,d);(a.options.scrollbar.liveRedraw||"mousemove"!==c.DOMType)&&setTimeout(function(){e.onMouseUp(c)})}));e.addBaseSeriesEvents();e.addChartEvents()},getUnionExtremes:function(a){var c=this.chart.xAxis[0],b=this.xAxis,d=b.options,l=c.options,h;a&&null===c.dataMin||(h={dataMin:g(d&&d.min,z("min",l.min,c.dataMin,b.dataMin,b.min)),dataMax:g(d&&d.max,z("max",l.max,c.dataMax,b.dataMax,b.max))});return h},setBaseSeries:function(a,
c){var b=this.chart,d=this.baseSeries=[];a=a||b.options&&b.options.navigator.baseSeries||0;r(b.series||[],function(c,b){c.options.isInternal||!c.options.showInNavigator&&(b!==a&&c.options.id!==a||!1===c.options.showInNavigator)||d.push(c)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(c)},updateNavigatorSeries:function(c){var b=this,l=b.chart,h=b.baseSeries,q,e,g=b.navigatorOptions.series,z,k={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",
yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,visible:!0},m=b.series=a.grep(b.series||[],function(c){var d=c.baseSeries;return 0>a.inArray(d,h)?(d&&(f(d,"updatedData",b.updatedDataHandler),delete d.navigatorSeries),c.destroy(),!1):!0});h&&h.length&&r(h,function(a){var f=a.navigatorSeries,v=d(g)?C.navigator.series:g;f&&!1===b.navigatorOptions.adaptToUpdatedData||(k.name="Navigator "+h.length,q=a.options||{},z=q.navigatorOptions||{},e=n(q,k,v,z),v=z.data||v.data,b.hasNavigatorData=
b.hasNavigatorData||!!v,e.data=v||q.data&&q.data.slice(0),f?f.update(e,c):(a.navigatorSeries=l.initSeries(e),a.navigatorSeries.baseSeries=a,m.push(a.navigatorSeries)))});if(g.data&&(!h||!h.length)||d(g))b.hasNavigatorData=!1,g=a.splat(g),r(g,function(a,c){k.name="Navigator "+(m.length+1);e=n(C.navigator.series,{color:l.series[c]&&!l.series[c].options.isInternal&&l.series[c].color||l.options.colors[c]||l.options.colors[0]},k,a);e.data=a.data;e.data&&(b.hasNavigatorData=!0,m.push(l.initSeries(e)))});
this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,c=a.baseSeries||[];c[0]&&c[0].xAxis&&m(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);r(c,function(c){m(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.show()});m(c,"hide",function(){this.navigatorSeries&&this.navigatorSeries.hide()});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&m(c,"updatedData",this.updatedDataHandler);m(c,"remove",function(){this.navigatorSeries&&(p(a.series,this.navigatorSeries),
this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,c;a.getExtremes&&(!(c=this.getUnionExtremes(!0))||c.dataMin===a.min&&c.dataMax===a.max||(a.min=c.dataMin,a.max=c.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,c=this.getExtremes(),b=c.dataMin,d=c.dataMax,c=c.max-c.min,l=a.stickToMin,h=a.stickToMax,f,g,z=a.series&&a.series[0],k=!!this.setExtremes;this.eventArgs&&"rangeSelectorButton"===this.eventArgs.trigger||
(l&&(g=b,f=g+c),h&&(f=d,l||(g=Math.max(f-c,z&&z.xData?z.xData[0]:-Number.MAX_VALUE))),k&&(l||h)&&e(g)&&(this.min=this.userMin=g,this.max=this.userMax=f));a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,c=this.navigatorSeries;a.stickToMax=Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=e(this.xAxis.min)&&this.xAxis.min<=this.xData[0]&&(!this.chart.fixedRange||!a.stickToMax);c&&!a.hasNavigatorData&&(c.options.pointStart=this.xData[0],c.setData(this.options.data,
!1,null,!1))},addChartEvents:function(){m(this.chart,"redraw",function(){var a=this.navigator,c=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);c&&a.render(c.min,c.max)})},destroy:function(){this.removeEvents();this.xAxis&&(p(this.chart.xAxis,this.xAxis),p(this.chart.axes,this.xAxis));this.yAxis&&(p(this.chart.yAxis,this.yAxis),p(this.chart.axes,this.yAxis));r(this.series||[],function(a){a.destroy&&a.destroy()});r("series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" "),
function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);r([this.handles],function(a){J(a)},this)}};a.Navigator=E;c(t.prototype,"zoom",function(a,c,b){var d=this.chart,l=d.options,h=l.chart.zoomType,e=l.navigator,l=l.rangeSelector,f;this.isXAxis&&(e&&e.enabled||l&&l.enabled)&&("x"===h?d.resetZoomButton="blocked":"y"===h?f=!1:"xy"===h&&(d=this.previousZoom,H(c)?this.previousZoom=[this.min,this.max]:d&&(c=d[0],b=d[1],delete this.previousZoom)));return void 0!==f?f:a.call(this,c,b)});
c(w.prototype,"init",function(a,c,b){m(this,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new E(this)});a.call(this,c,b)});c(w.prototype,"setChartSize",function(a){var c=this.legend,b=this.navigator,d,l,h,e;a.apply(this,[].slice.call(arguments,1));b&&(l=c.options,h=b.xAxis,e=b.yAxis,d=b.scrollbarHeight,this.inverted?(b.left=b.opposite?this.chartWidth-d-b.height:this.spacing[3]+d,b.top=this.plotTop+d):(b.left=this.plotLeft+d,b.top=
b.navigatorOptions.top||this.chartHeight-b.height-d-this.spacing[2]-("bottom"===l.verticalAlign&&l.enabled&&!l.floating?c.legendHeight+g(l.margin,10):0)),h&&e&&(this.inverted?h.options.left=e.options.left=b.left:h.options.top=e.options.top=b.top,h.setAxisSize(),e.setAxisSize()))});c(x.prototype,"addPoint",function(a,c,b,d,l){var h=this.options.turboThreshold;h&&this.xData.length>h&&F(c,!0)&&this.chart.navigator&&A(20,!0);a.call(this,c,b,d,l)});c(w.prototype,"addSeries",function(a,c,b,d){a=a.call(this,
c,!1,d);this.navigator&&this.navigator.setBaseSeries(null,!1);g(b,!0)&&this.redraw();return a});c(x.prototype,"update",function(a,c,b){a.call(this,c,!1);this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1);g(b,!0)&&this.chart.redraw()});w.prototype.callbacks.push(function(a){var c=a.navigator;c&&(a=a.xAxis[0].getExtremes(),c.render(a.min,a.max))})})(K);(function(a){function E(a){this.init(a)}var m=a.addEvent,t=a.Axis,w=a.Chart,C=a.css,H=a.createElement,J=a.dateFormat,
r=a.defaultOptions,p=r.global.useUTC,A=a.defined,G=a.destroyObjectProperties,k=a.discardElement,b=a.each,d=a.extend,e=a.fireEvent,F=a.Date,n=a.isNumber,g=a.merge,f=a.pick,B=a.pInt,x=a.splat,u=a.wrap;d(r,{rangeSelector:{buttonTheme:{"stroke-width":0,width:28,height:18,padding:2,zIndex:7},height:35,inputPosition:{align:"right"}}});r.lang=g(r.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});E.prototype={clickButton:function(a,d){var c=this,h=c.chart,e=c.buttonOptions[a],
g=h.xAxis[0],k=h.scroller&&h.scroller.getUnionExtremes()||g||{},I=k.dataMin,r=k.dataMax,u,y=g&&Math.round(Math.min(g.max,f(r,g.max))),w=e.type,L,k=e._range,A,N,C,B=e.dataGrouping;if(null!==I&&null!==r){h.fixedRange=k;B&&(this.forcedDataGrouping=!0,t.prototype.setDataGrouping.call(g||{chart:this.chart},B,!1));if("month"===w||"year"===w)g?(w={range:e,max:y,dataMin:I,dataMax:r},u=g.minFromRange.call(w),n(w.newMax)&&(y=w.newMax)):k=e;else if(k)u=Math.max(y-k,I),y=Math.min(u+k,r);else if("ytd"===w)if(g)void 0===
r&&(I=Number.MAX_VALUE,r=Number.MIN_VALUE,b(h.series,function(a){a=a.xData;I=Math.min(a[0],I);r=Math.max(a[a.length-1],r)}),d=!1),y=c.getYTDExtremes(r,I,p),u=A=y.min,y=y.max;else{m(h,"beforeRender",function(){c.clickButton(a)});return}else"all"===w&&g&&(u=I,y=r);c.setSelected(a);g?g.setExtremes(u,y,f(d,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:e}):(L=x(h.options.xAxis)[0],C=L.range,L.range=k,N=L.min,L.min=A,m(h,"load",function(){L.range=C;L.min=N}))}},setSelected:function(a){this.selected=
this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var c=this,d=a.options.rangeSelector,f=d.buttons||[].concat(c.defaultButtons),g=d.selected,k=function(){var a=c.minInput,b=c.maxInput;a&&a.blur&&e(a,"blur");b&&b.blur&&e(b,"blur")};c.chart=a;c.options=d;c.buttons=[];a.extraTopMargin=d.height;c.buttonOptions=f;this.unMouseDown=
m(a.container,"mousedown",k);this.unResize=m(a,"resize",k);b(f,c.computeButtonRange);void 0!==g&&f[g]&&this.clickButton(g,!1);m(a,"load",function(){m(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&c.forcedDataGrouping&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this.chart,d=a.xAxis[0],l=Math.round(d.max-d.min),e=!d.hasVisibleSeries,a=a.scroller&&a.scroller.getUnionExtremes()||d,f=a.dataMin,
g=a.dataMax,a=this.getYTDExtremes(g,f,p),k=a.min,m=a.max,t=this.selected,r=n(t),y=this.options.allButtonsEnabled,u=this.buttons;b(this.buttonOptions,function(a,c){var b=a._range,h=a.type,q=a.count||1;a=u[c];var z=0;c=c===t;var n=b>g-f,v=b<d.minRange,p=!1,I=!1,b=b===l;("month"===h||"year"===h)&&l>=864E5*{month:28,year:365}[h]*q&&l<=864E5*{month:31,year:366}[h]*q?b=!0:"ytd"===h?(b=m-k===l,p=!c):"all"===h&&(b=d.max-d.min>=g-f,I=!c&&r&&b);h=!y&&(n||v||I||e);b=c&&b||b&&!r&&!p;h?z=3:b&&(r=!0,z=2);a.state!==
z&&a.setState(z)})},computeButtonRange:function(a){var c=a.type,b=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[c])a._range=d[c]*b;else if("month"===c||"year"===c)a._range=864E5*{month:30,year:365}[c]*b},setInputValue:function(a,b){var c=this.chart.options.rangeSelector,d=this[a+"Input"];A(b)&&(d.previousValue=d.HCTime,d.HCTime=b);d.value=J(c.inputEditDateFormat||"%Y-%m-%d",d.HCTime);this[a+"DateBox"].attr({text:J(c.inputDateFormat||"%b %e, %Y",d.HCTime)})},
showInput:function(a){var c=this.inputGroup,b=this[a+"DateBox"];C(this[a+"Input"],{left:c.translateX+b.x+"px",top:c.translateY+"px",width:b.width-2+"px",height:b.height-2+"px",border:"2px solid silver"})},hideInput:function(a){C(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=m.value,b=(f.inputDateParser||Date.parse)(a),l=d.xAxis[0],h=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:l,e=h.dataMin,h=h.dataMax;b!==m.previousValue&&(m.previousValue=
b,n(b)||(b=a.split("-"),b=Date.UTC(B(b[0]),B(b[1])-1,B(b[2]))),n(b)&&(p||(b+=6E4*(new Date).getTimezoneOffset()),k?b>c.maxInput.HCTime?b=void 0:b<e&&(b=e):b<c.minInput.HCTime?b=void 0:b>h&&(b=h),void 0!==b&&l.setExtremes(k?b:l.min,k?l.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var c=this,d=c.chart,e=d.renderer,f=d.options.rangeSelector,g=c.div,k="min"===a,m,t,y=this.inputGroup;this[a+"Label"]=t=e.label(r.lang[k?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(y);
y.offset+=t.width+5;this[a+"DateBox"]=e=e.label("",y.offset).addClass("highcharts-range-input").attr({padding:2,width:f.inputBoxWidth||90,height:f.inputBoxHeight||17,stroke:f.inputBoxBorderColor||"#cccccc","stroke-width":1,"text-align":"center"}).on("click",function(){c.showInput(a);c[a+"Input"].focus()}).add(y);y.offset+=e.width+(k?10:0);this[a+"Input"]=m=H("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},g);m.onfocus=function(){c.showInput(a)};m.onblur=function(){c.hideInput(a)};
m.onchange=b;m.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector,a=f((b.buttonPosition||{}).y,a.plotTop-a.axisOffset[0]-b.height);return{buttonTop:a,inputTop:a-10}},getYTDExtremes:function(a,b,d){var c=new F(a),l=c[F.hcGetFullYear]();d=d?F.UTC(l,0,1):+new F(l,0,1);b=Math.max(b||0,d);c=c.getTime();return{max:Math.min(a||c,c),min:b}},render:function(a,h){var c=this,e=c.chart,g=e.renderer,k=e.container,n=e.options,m=n.exporting&&!1!==n.exporting.enabled&&
n.navigation&&n.navigation.buttonOptions,p=n.rangeSelector,t=c.buttons,n=r.lang,y=c.div,y=c.inputGroup,u=p.buttonTheme,w=p.buttonPosition||{},x=p.inputEnabled,C=u&&u.states,B=e.plotLeft,E,G=this.getPosition(),F=c.group,J=c.rendered;!1!==p.enabled&&(J||(c.group=F=g.g("range-selector-buttons").add(),c.zoomText=g.text(n.rangeSelectorZoom,f(w.x,B),15).css(p.labelStyle).add(F),E=f(w.x,B)+c.zoomText.getBBox().width+5,b(c.buttonOptions,function(a,b){t[b]=g.button(a.text,E,0,function(){c.clickButton(b);c.isActive=
!0},u,C&&C.hover,C&&C.select,C&&C.disabled).attr({"text-align":"center"}).add(F);E+=t[b].width+f(p.buttonSpacing,5)}),!1!==x&&(c.div=y=H("div",null,{position:"relative",height:0,zIndex:1}),k.parentNode.insertBefore(y,k),c.inputGroup=y=g.g("input-group").add(),y.offset=0,c.drawInput("min"),c.drawInput("max"))),c.updateButtonStates(),F[J?"animate":"attr"]({translateY:G.buttonTop}),!1!==x&&(y.align(d({y:G.inputTop,width:y.offset,x:m&&G.inputTop<(m.y||0)+m.height-e.spacing[0]?-40:0},p.inputPosition),
!0,e.spacingBox),A(x)||(e=F.getBBox(),y[y.alignAttr.translateX<e.x+e.width+10?"hide":"show"]()),c.setInputValue("min",a),c.setInputValue("max",h)),c.rendered=!0)},update:function(a){var b=this.chart;g(!0,b.options.rangeSelector,a);this.destroy();this.init(b)},destroy:function(){var b=this,d=b.minInput,l=b.maxInput;b.unMouseDown();b.unResize();G(b.buttons);d&&(d.onfocus=d.onblur=d.onchange=null);l&&(l.onfocus=l.onblur=l.onchange=null);a.objectEach(b,function(a,c){a&&"chart"!==c&&(a.destroy?a.destroy():
a.nodeType&&k(this[c]));a!==E.prototype[c]&&(b[c]=null)},this)}};t.prototype.toFixedRange=function(a,b,d,e){var c=this.chart&&this.chart.fixedRange;a=f(d,this.translate(a,!0,!this.horiz));b=f(e,this.translate(b,!0,!this.horiz));d=c&&(b-a)/c;.7<d&&1.3>d&&(e?a=b-c:b=a+c);n(a)||(a=b=void 0);return{min:a,max:b}};t.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],d,e=this.max,g,k,m=function(a,c){var d=new Date(a),e=d["get"+b]();d["set"+b](e+c);e===d["get"+b]()&&
d.setDate(0);return d.getTime()-a};n(a)?(d=e-a,k=a):(d=e+m(e,-a.count),this.chart&&(this.chart.fixedRange=e-d));g=f(this.dataMin,Number.MIN_VALUE);n(d)||(d=g);d<=g&&(d=g,void 0===k&&(k=m(d,a.count)),this.newMax=Math.min(d+k,this.dataMax));n(e)||(d=void 0);return d};u(w.prototype,"init",function(a,b,d){m(this,"init",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new E(this))});a.call(this,b,d)});w.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();n(c.min)&&
d.render(c.min,c.max)}var c,d=a.rangeSelector,e,f;d&&(f=m(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)}),e=m(a,"redraw",b),b());m(a,"destroy",function(){d&&(e(),f())})});a.RangeSelector=E})(K);(function(a){var E=a.arrayMax,m=a.arrayMin,t=a.Axis,w=a.Chart,C=a.defined,H=a.each,J=a.format,r=a.grep,p=a.inArray,A=a.isNumber,G=a.isString,k=a.map,b=a.merge,d=a.pick,e=a.Point,F=a.Series,n=a.splat,g=a.SVGRenderer,f=a.wrap,B=F.prototype,x=B.init,u=B.processData,c=e.prototype.tooltipFormatter;
a.StockChart=a.stockChart=function(c,e,f){var h=G(c)||c.nodeName,l=arguments[h?1:0],g=l.series,m=a.getOptions(),p,z=d(l.navigator&&l.navigator.enabled,m.navigator.enabled,!0),t=z?{startOnTick:!1,endOnTick:!1}:null,r={marker:{enabled:!1,radius:2}},u={shadow:!1,borderWidth:0};l.xAxis=k(n(l.xAxis||{}),function(a){return b({minPadding:0,maxPadding:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},m.xAxis,a,{type:"datetime",categories:null},t)});l.yAxis=k(n(l.yAxis||{}),function(a){p=
d(a.opposite,!0);return b({labels:{y:-2},opposite:p,showLastLabel:!1,title:{text:null}},m.yAxis,a)});l.series=null;l=b({chart:{panning:!0,pinchType:"x"},navigator:{enabled:z},scrollbar:{enabled:d(m.scrollbar.enabled,!0)},rangeSelector:{enabled:d(m.rangeSelector.enabled,!0)},title:{text:null},tooltip:{shared:!0,crosshairs:!0},legend:{enabled:!1},plotOptions:{line:r,spline:r,area:r,areaspline:r,arearange:r,areasplinerange:r,column:u,columnrange:u,candlestick:u,ohlc:u}},l,{isStock:!0});l.series=g;return h?
new w(c,l,f):new w(l,e)};f(t.prototype,"autoLabelAlign",function(a){var b=this.chart,c=this.options,b=b._labelPanes=b._labelPanes||{},d=this.options.labels;return this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled)?(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,"right"):a.apply(this,[].slice.call(arguments,1))});f(t.prototype,"destroy",function(a){var b=this.chart,c=this.options&&this.options.top+","+this.options.height;c&&b._labelPanes&&b._labelPanes[c]===
this&&delete b._labelPanes[c];return a.apply(this,Array.prototype.slice.call(arguments,1))});f(t.prototype,"getPlotLinePath",function(b,c,e,f,g,m){var h=this,l=this.isLinked&&!this.series?this.linkedParent.series:this.series,q=h.chart,n=q.renderer,t=h.left,r=h.top,v,z,u,w,x=[],D=[],B,E;if("xAxis"!==h.coll&&"yAxis"!==h.coll)return b.apply(this,[].slice.call(arguments,1));D=function(a){var b="xAxis"===a?"yAxis":"xAxis";a=h.options[b];return A(a)?[q[b][a]]:G(a)?[q.get(a)]:k(l,function(a){return a[b]})}(h.coll);
H(h.isXAxis?q.yAxis:q.xAxis,function(a){if(C(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis",b=C(a.options[b])?q[b][a.options[b]]:q[b][0];h===b&&D.push(a)}});B=D.length?[]:[h.isXAxis?q.yAxis[0]:q.xAxis[0]];H(D,function(b){-1!==p(b,B)||a.find(B,function(a){return a.pos===b.pos&&a.len&&b.len})||B.push(b)});E=d(m,h.translate(c,null,null,f));A(E)&&(h.horiz?H(B,function(a){var b;z=a.pos;w=z+a.len;v=u=Math.round(E+h.transB);if(v<t||v>t+h.width)g?v=u=Math.min(Math.max(t,
v),t+h.width):b=!0;b||x.push("M",v,z,"L",u,w)}):H(B,function(a){var b;v=a.pos;u=v+a.len;z=w=Math.round(r+h.height-E);if(z<r||z>r+h.height)g?z=w=Math.min(Math.max(r,z),h.top+h.height):b=!0;b||x.push("M",v,z,"L",u,w)}));return 0<x.length?n.crispPolyLine(x,e||1):null});t.prototype.getPlotBandPath=function(a,b){b=this.getPlotLinePath(b,null,null,!0);a=this.getPlotLinePath(a,null,null,!0);var c=[],d;if(a&&b)if(a.toString()===b.toString())c=a,c.flat=!0;else for(d=0;d<a.length;d+=6)c.push("M",a[d+1],a[d+
2],"L",a[d+4],a[d+5],b[d+4],b[d+5],b[d+1],b[d+2],"z");else c=null;return c};g.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};f(t.prototype,"hideCrosshair",function(a,b){a.call(this,b);this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});f(t.prototype,"drawCrosshair",function(a,b,c){var e,f;a.call(this,b,c);if(C(this.crosshair.label)&&this.crosshair.label.enabled&&
this.cross){a=this.chart;var h=this.options.crosshair.label,g=this.horiz;e=this.opposite;f=this.left;var l=this.top,k=this.crossLabel,m,n=h.format,p="",t="inside"===this.options.tickPosition,r=!1!==this.crosshair.snap,u=0;b||(b=this.cross&&this.cross.e);m=g?"center":e?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";k||(k=this.crossLabel=a.renderer.label(null,null,null,h.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+
this.series[0].colorIndex)).attr({align:h.align||m,padding:d(h.padding,8),r:d(h.borderRadius,3),zIndex:2}).add(this.labelGroup));g?(m=r?c.plotX+f:b.chartX,l+=e?0:this.height):(m=e?this.width+f:0,l=r?c.plotY+l:b.chartY);n||h.formatter||(this.isDatetimeAxis&&(p="%b %d, %Y"),n="{value"+(p?":"+p:"")+"}");b=r?c[this.isXAxis?"x":"y"]:this.toValue(g?b.chartX:b.chartY);k.attr({text:n?J(n,{value:b}):h.formatter.call(this,b),x:m,y:l,visibility:"visible"});b=k.getBBox();if(g){if(t&&!e||!t&&e)l=k.y-b.height}else l=
k.y-b.height/2;g?(e=f-b.x,f=f+this.width-b.x):(e="left"===this.labelAlign?f:0,f="right"===this.labelAlign?f+this.width:a.chartWidth);k.translateX<e&&(u=e-k.translateX);k.translateX+b.width>=f&&(u=-(k.translateX+b.width-f));k.attr({x:m+u,y:l,anchorX:g?m:this.opposite?0:a.chartWidth,anchorY:g?this.opposite?a.chartHeight:0:l+b.height/2})}});B.init=function(){x.apply(this,arguments);this.setCompare(this.options.compare)};B.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,
c){var d=this.compareValue;if(void 0!==b&&void 0!==d)return b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};B.processData=function(){var a,b=-1,c,d,e,f;u.apply(this,arguments);if(this.xAxis&&this.processedYData)for(c=this.processedXData,d=this.processedYData,e=d.length,this.pointArrayMap&&(b=p("close",this.pointArrayMap),-1===b&&(b=p(this.pointValKey||"y",this.pointArrayMap))),a=0;a<e-1;a++)if(f=
d[a]&&-1<b?d[a][b]:d[a],A(f)&&c[a+1]>=this.xAxis.min&&0!==f){this.compareValue=f;break}};f(B,"getExtremes",function(a){var b;a.apply(this,[].slice.call(arguments,1));this.modifyValue&&(b=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)],this.dataMin=m(b),this.dataMax=E(b))});t.prototype.setCompare=function(a,b){this.isXAxis||(H(this.series,function(b){b.setCompare(a)}),d(b,!0)&&this.chart.redraw())};e.prototype.tooltipFormatter=function(b){b=b.replace("{point.change}",(0<this.change?
"+":"")+a.numberFormat(this.change,d(this.series.tooltipOptions.changeDecimals,2)));return c.apply(this,[b])};f(F.prototype,"render",function(a){this.chart.is3d&&this.chart.is3d()||this.chart.polar||!this.xAxis||this.xAxis.isRadial||(!this.clipBox&&this.animate?(this.clipBox=b(this.chart.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=this.yAxis.len):this.chart[this.sharedClipKey]?this.chart[this.sharedClipKey].attr({width:this.xAxis.len,height:this.yAxis.len}):this.clipBox&&(this.clipBox.width=
this.xAxis.len,this.clipBox.height=this.yAxis.len));a.call(this)});f(w.prototype,"getSelectedPoints",function(a){var b=a.call(this);H(this.series,function(a){a.hasGroupedData&&(b=b.concat(r(a.points||[],function(a){return a.selected})))});return b});f(w.prototype,"update",function(a,c){"scrollbar"in c&&this.navigator&&(b(!0,this.options.scrollbar,c.scrollbar),this.navigator.update({},!1),delete c.scrollbar);return a.apply(this,Array.prototype.slice.call(arguments,1))})})(K)});